-- this is generated by luajitffi
local ffi = require('ffi')
---@type Table<string, integer>
local C = ffi.C

local M = {
    libs = {},
    cache = {},
}

-- cdef
require('clang.cdef.corecrt')
require('clang.cdef.vcruntime')
require('clang.cdef.Index')
require('clang.cdef.CXErrorCode')
require('clang.cdef.CXString')
M.enums = {
    CXAvailabilityKind = {
        CXAvailability_Available = C.CXAvailability_Available,
        CXAvailability_Deprecated = C.CXAvailability_Deprecated,
        CXAvailability_NotAvailable = C.CXAvailability_NotAvailable,
        CXAvailability_NotAccessible = C.CXAvailability_NotAccessible,
    },
    CXCursor_ExceptionSpecificationKind = {
        CXCursor_ExceptionSpecificationKind_None = C.CXCursor_ExceptionSpecificationKind_None,
        CXCursor_ExceptionSpecificationKind_DynamicNone = C.CXCursor_ExceptionSpecificationKind_DynamicNone,
        CXCursor_ExceptionSpecificationKind_Dynamic = C.CXCursor_ExceptionSpecificationKind_Dynamic,
        CXCursor_ExceptionSpecificationKind_MSAny = C.CXCursor_ExceptionSpecificationKind_MSAny,
        CXCursor_ExceptionSpecificationKind_BasicNoexcept = C.CXCursor_ExceptionSpecificationKind_BasicNoexcept,
        CXCursor_ExceptionSpecificationKind_ComputedNoexcept = C.CXCursor_ExceptionSpecificationKind_ComputedNoexcept,
        CXCursor_ExceptionSpecificationKind_Unevaluated = C.CXCursor_ExceptionSpecificationKind_Unevaluated,
        CXCursor_ExceptionSpecificationKind_Uninstantiated = C.CXCursor_ExceptionSpecificationKind_Uninstantiated,
        CXCursor_ExceptionSpecificationKind_Unparsed = C.CXCursor_ExceptionSpecificationKind_Unparsed,
        CXCursor_ExceptionSpecificationKind_NoThrow = C.CXCursor_ExceptionSpecificationKind_NoThrow,
    },
    CXDiagnosticSeverity = {
        CXDiagnostic_Ignored = C.CXDiagnostic_Ignored,
        CXDiagnostic_Note = C.CXDiagnostic_Note,
        CXDiagnostic_Warning = C.CXDiagnostic_Warning,
        CXDiagnostic_Error = C.CXDiagnostic_Error,
        CXDiagnostic_Fatal = C.CXDiagnostic_Fatal,
    },
    CXLoadDiag_Error = {
        CXLoadDiag_None = C.CXLoadDiag_None,
        CXLoadDiag_Unknown = C.CXLoadDiag_Unknown,
        CXLoadDiag_CannotLoad = C.CXLoadDiag_CannotLoad,
        CXLoadDiag_InvalidFile = C.CXLoadDiag_InvalidFile,
    },
    CXDiagnosticDisplayOptions = {
        CXDiagnostic_DisplaySourceLocation = C.CXDiagnostic_DisplaySourceLocation,
        CXDiagnostic_DisplayColumn = C.CXDiagnostic_DisplayColumn,
        CXDiagnostic_DisplaySourceRanges = C.CXDiagnostic_DisplaySourceRanges,
        CXDiagnostic_DisplayOption = C.CXDiagnostic_DisplayOption,
        CXDiagnostic_DisplayCategoryId = C.CXDiagnostic_DisplayCategoryId,
        CXDiagnostic_DisplayCategoryName = C.CXDiagnostic_DisplayCategoryName,
    },
    CXTranslationUnit_Flags = {
        CXTranslationUnit_None = C.CXTranslationUnit_None,
        CXTranslationUnit_DetailedPreprocessingRecord = C.CXTranslationUnit_DetailedPreprocessingRecord,
        CXTranslationUnit_Incomplete = C.CXTranslationUnit_Incomplete,
        CXTranslationUnit_PrecompiledPreamble = C.CXTranslationUnit_PrecompiledPreamble,
        CXTranslationUnit_CacheCompletionResults = C.CXTranslationUnit_CacheCompletionResults,
        CXTranslationUnit_ForSerialization = C.CXTranslationUnit_ForSerialization,
        CXTranslationUnit_CXXChainedPCH = C.CXTranslationUnit_CXXChainedPCH,
        CXTranslationUnit_SkipFunctionBodies = C.CXTranslationUnit_SkipFunctionBodies,
        CXTranslationUnit_IncludeBriefCommentsInCodeCompletion = C.CXTranslationUnit_IncludeBriefCommentsInCodeCompletion,
        CXTranslationUnit_CreatePreambleOnFirstParse = C.CXTranslationUnit_CreatePreambleOnFirstParse,
        CXTranslationUnit_KeepGoing = C.CXTranslationUnit_KeepGoing,
        CXTranslationUnit_SingleFileParse = C.CXTranslationUnit_SingleFileParse,
        CXTranslationUnit_LimitSkipFunctionBodiesToPreamble = C.CXTranslationUnit_LimitSkipFunctionBodiesToPreamble,
        CXTranslationUnit_IncludeAttributedTypes = C.CXTranslationUnit_IncludeAttributedTypes,
        CXTranslationUnit_VisitImplicitAttributes = C.CXTranslationUnit_VisitImplicitAttributes,
        CXTranslationUnit_IgnoreNonErrorsFromIncludedFiles = C.CXTranslationUnit_IgnoreNonErrorsFromIncludedFiles,
        CXTranslationUnit_RetainExcludedConditionalBlocks = C.CXTranslationUnit_RetainExcludedConditionalBlocks,
    },
    CXSaveTranslationUnit_Flags = {
        CXSaveTranslationUnit_None = C.CXSaveTranslationUnit_None,
    },
    CXSaveError = {
        CXSaveError_None = C.CXSaveError_None,
        CXSaveError_Unknown = C.CXSaveError_Unknown,
        CXSaveError_TranslationErrors = C.CXSaveError_TranslationErrors,
        CXSaveError_InvalidTU = C.CXSaveError_InvalidTU,
    },
    CXReparse_Flags = {
        CXReparse_None = C.CXReparse_None,
    },
    CXTUResourceUsageKind = {
        CXTUResourceUsage_AST = C.CXTUResourceUsage_AST,
        CXTUResourceUsage_Identifiers = C.CXTUResourceUsage_Identifiers,
        CXTUResourceUsage_Selectors = C.CXTUResourceUsage_Selectors,
        CXTUResourceUsage_GlobalCompletionResults = C.CXTUResourceUsage_GlobalCompletionResults,
        CXTUResourceUsage_SourceManagerContentCache = C.CXTUResourceUsage_SourceManagerContentCache,
        CXTUResourceUsage_AST_SideTables = C.CXTUResourceUsage_AST_SideTables,
        CXTUResourceUsage_SourceManager_Membuffer_Malloc = C.CXTUResourceUsage_SourceManager_Membuffer_Malloc,
        CXTUResourceUsage_SourceManager_Membuffer_MMap = C.CXTUResourceUsage_SourceManager_Membuffer_MMap,
        CXTUResourceUsage_ExternalASTSource_Membuffer_Malloc = C.CXTUResourceUsage_ExternalASTSource_Membuffer_Malloc,
        CXTUResourceUsage_ExternalASTSource_Membuffer_MMap = C.CXTUResourceUsage_ExternalASTSource_Membuffer_MMap,
        CXTUResourceUsage_Preprocessor = C.CXTUResourceUsage_Preprocessor,
        CXTUResourceUsage_PreprocessingRecord = C.CXTUResourceUsage_PreprocessingRecord,
        CXTUResourceUsage_SourceManager_DataStructures = C.CXTUResourceUsage_SourceManager_DataStructures,
        CXTUResourceUsage_Preprocessor_HeaderSearch = C.CXTUResourceUsage_Preprocessor_HeaderSearch,
        CXTUResourceUsage_MEMORY_IN_BYTES_BEGIN = C.CXTUResourceUsage_MEMORY_IN_BYTES_BEGIN,
        CXTUResourceUsage_MEMORY_IN_BYTES_END = C.CXTUResourceUsage_MEMORY_IN_BYTES_END,
        CXTUResourceUsage_First = C.CXTUResourceUsage_First,
        CXTUResourceUsage_Last = C.CXTUResourceUsage_Last,
    },
    CXCursorKind = {
        CXCursor_UnexposedDecl = C.CXCursor_UnexposedDecl,
        CXCursor_StructDecl = C.CXCursor_StructDecl,
        CXCursor_UnionDecl = C.CXCursor_UnionDecl,
        CXCursor_ClassDecl = C.CXCursor_ClassDecl,
        CXCursor_EnumDecl = C.CXCursor_EnumDecl,
        CXCursor_FieldDecl = C.CXCursor_FieldDecl,
        CXCursor_EnumConstantDecl = C.CXCursor_EnumConstantDecl,
        CXCursor_FunctionDecl = C.CXCursor_FunctionDecl,
        CXCursor_VarDecl = C.CXCursor_VarDecl,
        CXCursor_ParmDecl = C.CXCursor_ParmDecl,
        CXCursor_ObjCInterfaceDecl = C.CXCursor_ObjCInterfaceDecl,
        CXCursor_ObjCCategoryDecl = C.CXCursor_ObjCCategoryDecl,
        CXCursor_ObjCProtocolDecl = C.CXCursor_ObjCProtocolDecl,
        CXCursor_ObjCPropertyDecl = C.CXCursor_ObjCPropertyDecl,
        CXCursor_ObjCIvarDecl = C.CXCursor_ObjCIvarDecl,
        CXCursor_ObjCInstanceMethodDecl = C.CXCursor_ObjCInstanceMethodDecl,
        CXCursor_ObjCClassMethodDecl = C.CXCursor_ObjCClassMethodDecl,
        CXCursor_ObjCImplementationDecl = C.CXCursor_ObjCImplementationDecl,
        CXCursor_ObjCCategoryImplDecl = C.CXCursor_ObjCCategoryImplDecl,
        CXCursor_TypedefDecl = C.CXCursor_TypedefDecl,
        CXCursor_CXXMethod = C.CXCursor_CXXMethod,
        CXCursor_Namespace = C.CXCursor_Namespace,
        CXCursor_LinkageSpec = C.CXCursor_LinkageSpec,
        CXCursor_Constructor = C.CXCursor_Constructor,
        CXCursor_Destructor = C.CXCursor_Destructor,
        CXCursor_ConversionFunction = C.CXCursor_ConversionFunction,
        CXCursor_TemplateTypeParameter = C.CXCursor_TemplateTypeParameter,
        CXCursor_NonTypeTemplateParameter = C.CXCursor_NonTypeTemplateParameter,
        CXCursor_TemplateTemplateParameter = C.CXCursor_TemplateTemplateParameter,
        CXCursor_FunctionTemplate = C.CXCursor_FunctionTemplate,
        CXCursor_ClassTemplate = C.CXCursor_ClassTemplate,
        CXCursor_ClassTemplatePartialSpecialization = C.CXCursor_ClassTemplatePartialSpecialization,
        CXCursor_NamespaceAlias = C.CXCursor_NamespaceAlias,
        CXCursor_UsingDirective = C.CXCursor_UsingDirective,
        CXCursor_UsingDeclaration = C.CXCursor_UsingDeclaration,
        CXCursor_TypeAliasDecl = C.CXCursor_TypeAliasDecl,
        CXCursor_ObjCSynthesizeDecl = C.CXCursor_ObjCSynthesizeDecl,
        CXCursor_ObjCDynamicDecl = C.CXCursor_ObjCDynamicDecl,
        CXCursor_CXXAccessSpecifier = C.CXCursor_CXXAccessSpecifier,
        CXCursor_FirstDecl = C.CXCursor_FirstDecl,
        CXCursor_LastDecl = C.CXCursor_LastDecl,
        CXCursor_FirstRef = C.CXCursor_FirstRef,
        CXCursor_ObjCSuperClassRef = C.CXCursor_ObjCSuperClassRef,
        CXCursor_ObjCProtocolRef = C.CXCursor_ObjCProtocolRef,
        CXCursor_ObjCClassRef = C.CXCursor_ObjCClassRef,
        CXCursor_TypeRef = C.CXCursor_TypeRef,
        CXCursor_CXXBaseSpecifier = C.CXCursor_CXXBaseSpecifier,
        CXCursor_TemplateRef = C.CXCursor_TemplateRef,
        CXCursor_NamespaceRef = C.CXCursor_NamespaceRef,
        CXCursor_MemberRef = C.CXCursor_MemberRef,
        CXCursor_LabelRef = C.CXCursor_LabelRef,
        CXCursor_OverloadedDeclRef = C.CXCursor_OverloadedDeclRef,
        CXCursor_VariableRef = C.CXCursor_VariableRef,
        CXCursor_LastRef = C.CXCursor_LastRef,
        CXCursor_FirstInvalid = C.CXCursor_FirstInvalid,
        CXCursor_InvalidFile = C.CXCursor_InvalidFile,
        CXCursor_NoDeclFound = C.CXCursor_NoDeclFound,
        CXCursor_NotImplemented = C.CXCursor_NotImplemented,
        CXCursor_InvalidCode = C.CXCursor_InvalidCode,
        CXCursor_LastInvalid = C.CXCursor_LastInvalid,
        CXCursor_FirstExpr = C.CXCursor_FirstExpr,
        CXCursor_UnexposedExpr = C.CXCursor_UnexposedExpr,
        CXCursor_DeclRefExpr = C.CXCursor_DeclRefExpr,
        CXCursor_MemberRefExpr = C.CXCursor_MemberRefExpr,
        CXCursor_CallExpr = C.CXCursor_CallExpr,
        CXCursor_ObjCMessageExpr = C.CXCursor_ObjCMessageExpr,
        CXCursor_BlockExpr = C.CXCursor_BlockExpr,
        CXCursor_IntegerLiteral = C.CXCursor_IntegerLiteral,
        CXCursor_FloatingLiteral = C.CXCursor_FloatingLiteral,
        CXCursor_ImaginaryLiteral = C.CXCursor_ImaginaryLiteral,
        CXCursor_StringLiteral = C.CXCursor_StringLiteral,
        CXCursor_CharacterLiteral = C.CXCursor_CharacterLiteral,
        CXCursor_ParenExpr = C.CXCursor_ParenExpr,
        CXCursor_UnaryOperator = C.CXCursor_UnaryOperator,
        CXCursor_ArraySubscriptExpr = C.CXCursor_ArraySubscriptExpr,
        CXCursor_BinaryOperator = C.CXCursor_BinaryOperator,
        CXCursor_CompoundAssignOperator = C.CXCursor_CompoundAssignOperator,
        CXCursor_ConditionalOperator = C.CXCursor_ConditionalOperator,
        CXCursor_CStyleCastExpr = C.CXCursor_CStyleCastExpr,
        CXCursor_CompoundLiteralExpr = C.CXCursor_CompoundLiteralExpr,
        CXCursor_InitListExpr = C.CXCursor_InitListExpr,
        CXCursor_AddrLabelExpr = C.CXCursor_AddrLabelExpr,
        CXCursor_StmtExpr = C.CXCursor_StmtExpr,
        CXCursor_GenericSelectionExpr = C.CXCursor_GenericSelectionExpr,
        CXCursor_GNUNullExpr = C.CXCursor_GNUNullExpr,
        CXCursor_CXXStaticCastExpr = C.CXCursor_CXXStaticCastExpr,
        CXCursor_CXXDynamicCastExpr = C.CXCursor_CXXDynamicCastExpr,
        CXCursor_CXXReinterpretCastExpr = C.CXCursor_CXXReinterpretCastExpr,
        CXCursor_CXXConstCastExpr = C.CXCursor_CXXConstCastExpr,
        CXCursor_CXXFunctionalCastExpr = C.CXCursor_CXXFunctionalCastExpr,
        CXCursor_CXXAddrspaceCastExpr = C.CXCursor_CXXAddrspaceCastExpr,
        CXCursor_CXXTypeidExpr = C.CXCursor_CXXTypeidExpr,
        CXCursor_CXXBoolLiteralExpr = C.CXCursor_CXXBoolLiteralExpr,
        CXCursor_CXXNullPtrLiteralExpr = C.CXCursor_CXXNullPtrLiteralExpr,
        CXCursor_CXXThisExpr = C.CXCursor_CXXThisExpr,
        CXCursor_CXXThrowExpr = C.CXCursor_CXXThrowExpr,
        CXCursor_CXXNewExpr = C.CXCursor_CXXNewExpr,
        CXCursor_CXXDeleteExpr = C.CXCursor_CXXDeleteExpr,
        CXCursor_UnaryExpr = C.CXCursor_UnaryExpr,
        CXCursor_ObjCStringLiteral = C.CXCursor_ObjCStringLiteral,
        CXCursor_ObjCEncodeExpr = C.CXCursor_ObjCEncodeExpr,
        CXCursor_ObjCSelectorExpr = C.CXCursor_ObjCSelectorExpr,
        CXCursor_ObjCProtocolExpr = C.CXCursor_ObjCProtocolExpr,
        CXCursor_ObjCBridgedCastExpr = C.CXCursor_ObjCBridgedCastExpr,
        CXCursor_PackExpansionExpr = C.CXCursor_PackExpansionExpr,
        CXCursor_SizeOfPackExpr = C.CXCursor_SizeOfPackExpr,
        CXCursor_LambdaExpr = C.CXCursor_LambdaExpr,
        CXCursor_ObjCBoolLiteralExpr = C.CXCursor_ObjCBoolLiteralExpr,
        CXCursor_ObjCSelfExpr = C.CXCursor_ObjCSelfExpr,
        CXCursor_OMPArraySectionExpr = C.CXCursor_OMPArraySectionExpr,
        CXCursor_ObjCAvailabilityCheckExpr = C.CXCursor_ObjCAvailabilityCheckExpr,
        CXCursor_FixedPointLiteral = C.CXCursor_FixedPointLiteral,
        CXCursor_OMPArrayShapingExpr = C.CXCursor_OMPArrayShapingExpr,
        CXCursor_OMPIteratorExpr = C.CXCursor_OMPIteratorExpr,
        CXCursor_LastExpr = C.CXCursor_LastExpr,
        CXCursor_FirstStmt = C.CXCursor_FirstStmt,
        CXCursor_UnexposedStmt = C.CXCursor_UnexposedStmt,
        CXCursor_LabelStmt = C.CXCursor_LabelStmt,
        CXCursor_CompoundStmt = C.CXCursor_CompoundStmt,
        CXCursor_CaseStmt = C.CXCursor_CaseStmt,
        CXCursor_DefaultStmt = C.CXCursor_DefaultStmt,
        CXCursor_IfStmt = C.CXCursor_IfStmt,
        CXCursor_SwitchStmt = C.CXCursor_SwitchStmt,
        CXCursor_WhileStmt = C.CXCursor_WhileStmt,
        CXCursor_DoStmt = C.CXCursor_DoStmt,
        CXCursor_ForStmt = C.CXCursor_ForStmt,
        CXCursor_GotoStmt = C.CXCursor_GotoStmt,
        CXCursor_IndirectGotoStmt = C.CXCursor_IndirectGotoStmt,
        CXCursor_ContinueStmt = C.CXCursor_ContinueStmt,
        CXCursor_BreakStmt = C.CXCursor_BreakStmt,
        CXCursor_ReturnStmt = C.CXCursor_ReturnStmt,
        CXCursor_GCCAsmStmt = C.CXCursor_GCCAsmStmt,
        CXCursor_AsmStmt = C.CXCursor_AsmStmt,
        CXCursor_ObjCAtTryStmt = C.CXCursor_ObjCAtTryStmt,
        CXCursor_ObjCAtCatchStmt = C.CXCursor_ObjCAtCatchStmt,
        CXCursor_ObjCAtFinallyStmt = C.CXCursor_ObjCAtFinallyStmt,
        CXCursor_ObjCAtThrowStmt = C.CXCursor_ObjCAtThrowStmt,
        CXCursor_ObjCAtSynchronizedStmt = C.CXCursor_ObjCAtSynchronizedStmt,
        CXCursor_ObjCAutoreleasePoolStmt = C.CXCursor_ObjCAutoreleasePoolStmt,
        CXCursor_ObjCForCollectionStmt = C.CXCursor_ObjCForCollectionStmt,
        CXCursor_CXXCatchStmt = C.CXCursor_CXXCatchStmt,
        CXCursor_CXXTryStmt = C.CXCursor_CXXTryStmt,
        CXCursor_CXXForRangeStmt = C.CXCursor_CXXForRangeStmt,
        CXCursor_SEHTryStmt = C.CXCursor_SEHTryStmt,
        CXCursor_SEHExceptStmt = C.CXCursor_SEHExceptStmt,
        CXCursor_SEHFinallyStmt = C.CXCursor_SEHFinallyStmt,
        CXCursor_MSAsmStmt = C.CXCursor_MSAsmStmt,
        CXCursor_NullStmt = C.CXCursor_NullStmt,
        CXCursor_DeclStmt = C.CXCursor_DeclStmt,
        CXCursor_OMPParallelDirective = C.CXCursor_OMPParallelDirective,
        CXCursor_OMPSimdDirective = C.CXCursor_OMPSimdDirective,
        CXCursor_OMPForDirective = C.CXCursor_OMPForDirective,
        CXCursor_OMPSectionsDirective = C.CXCursor_OMPSectionsDirective,
        CXCursor_OMPSectionDirective = C.CXCursor_OMPSectionDirective,
        CXCursor_OMPSingleDirective = C.CXCursor_OMPSingleDirective,
        CXCursor_OMPParallelForDirective = C.CXCursor_OMPParallelForDirective,
        CXCursor_OMPParallelSectionsDirective = C.CXCursor_OMPParallelSectionsDirective,
        CXCursor_OMPTaskDirective = C.CXCursor_OMPTaskDirective,
        CXCursor_OMPMasterDirective = C.CXCursor_OMPMasterDirective,
        CXCursor_OMPCriticalDirective = C.CXCursor_OMPCriticalDirective,
        CXCursor_OMPTaskyieldDirective = C.CXCursor_OMPTaskyieldDirective,
        CXCursor_OMPBarrierDirective = C.CXCursor_OMPBarrierDirective,
        CXCursor_OMPTaskwaitDirective = C.CXCursor_OMPTaskwaitDirective,
        CXCursor_OMPFlushDirective = C.CXCursor_OMPFlushDirective,
        CXCursor_SEHLeaveStmt = C.CXCursor_SEHLeaveStmt,
        CXCursor_OMPOrderedDirective = C.CXCursor_OMPOrderedDirective,
        CXCursor_OMPAtomicDirective = C.CXCursor_OMPAtomicDirective,
        CXCursor_OMPForSimdDirective = C.CXCursor_OMPForSimdDirective,
        CXCursor_OMPParallelForSimdDirective = C.CXCursor_OMPParallelForSimdDirective,
        CXCursor_OMPTargetDirective = C.CXCursor_OMPTargetDirective,
        CXCursor_OMPTeamsDirective = C.CXCursor_OMPTeamsDirective,
        CXCursor_OMPTaskgroupDirective = C.CXCursor_OMPTaskgroupDirective,
        CXCursor_OMPCancellationPointDirective = C.CXCursor_OMPCancellationPointDirective,
        CXCursor_OMPCancelDirective = C.CXCursor_OMPCancelDirective,
        CXCursor_OMPTargetDataDirective = C.CXCursor_OMPTargetDataDirective,
        CXCursor_OMPTaskLoopDirective = C.CXCursor_OMPTaskLoopDirective,
        CXCursor_OMPTaskLoopSimdDirective = C.CXCursor_OMPTaskLoopSimdDirective,
        CXCursor_OMPDistributeDirective = C.CXCursor_OMPDistributeDirective,
        CXCursor_OMPTargetEnterDataDirective = C.CXCursor_OMPTargetEnterDataDirective,
        CXCursor_OMPTargetExitDataDirective = C.CXCursor_OMPTargetExitDataDirective,
        CXCursor_OMPTargetParallelDirective = C.CXCursor_OMPTargetParallelDirective,
        CXCursor_OMPTargetParallelForDirective = C.CXCursor_OMPTargetParallelForDirective,
        CXCursor_OMPTargetUpdateDirective = C.CXCursor_OMPTargetUpdateDirective,
        CXCursor_OMPDistributeParallelForDirective = C.CXCursor_OMPDistributeParallelForDirective,
        CXCursor_OMPDistributeParallelForSimdDirective = C.CXCursor_OMPDistributeParallelForSimdDirective,
        CXCursor_OMPDistributeSimdDirective = C.CXCursor_OMPDistributeSimdDirective,
        CXCursor_OMPTargetParallelForSimdDirective = C.CXCursor_OMPTargetParallelForSimdDirective,
        CXCursor_OMPTargetSimdDirective = C.CXCursor_OMPTargetSimdDirective,
        CXCursor_OMPTeamsDistributeDirective = C.CXCursor_OMPTeamsDistributeDirective,
        CXCursor_OMPTeamsDistributeSimdDirective = C.CXCursor_OMPTeamsDistributeSimdDirective,
        CXCursor_OMPTeamsDistributeParallelForSimdDirective = C.CXCursor_OMPTeamsDistributeParallelForSimdDirective,
        CXCursor_OMPTeamsDistributeParallelForDirective = C.CXCursor_OMPTeamsDistributeParallelForDirective,
        CXCursor_OMPTargetTeamsDirective = C.CXCursor_OMPTargetTeamsDirective,
        CXCursor_OMPTargetTeamsDistributeDirective = C.CXCursor_OMPTargetTeamsDistributeDirective,
        CXCursor_OMPTargetTeamsDistributeParallelForDirective = C.CXCursor_OMPTargetTeamsDistributeParallelForDirective,
        CXCursor_OMPTargetTeamsDistributeParallelForSimdDirective = C.CXCursor_OMPTargetTeamsDistributeParallelForSimdDirective,
        CXCursor_OMPTargetTeamsDistributeSimdDirective = C.CXCursor_OMPTargetTeamsDistributeSimdDirective,
        CXCursor_BuiltinBitCastExpr = C.CXCursor_BuiltinBitCastExpr,
        CXCursor_OMPMasterTaskLoopDirective = C.CXCursor_OMPMasterTaskLoopDirective,
        CXCursor_OMPParallelMasterTaskLoopDirective = C.CXCursor_OMPParallelMasterTaskLoopDirective,
        CXCursor_OMPMasterTaskLoopSimdDirective = C.CXCursor_OMPMasterTaskLoopSimdDirective,
        CXCursor_OMPParallelMasterTaskLoopSimdDirective = C.CXCursor_OMPParallelMasterTaskLoopSimdDirective,
        CXCursor_OMPParallelMasterDirective = C.CXCursor_OMPParallelMasterDirective,
        CXCursor_OMPDepobjDirective = C.CXCursor_OMPDepobjDirective,
        CXCursor_OMPScanDirective = C.CXCursor_OMPScanDirective,
        CXCursor_LastStmt = C.CXCursor_LastStmt,
        CXCursor_TranslationUnit = C.CXCursor_TranslationUnit,
        CXCursor_FirstAttr = C.CXCursor_FirstAttr,
        CXCursor_UnexposedAttr = C.CXCursor_UnexposedAttr,
        CXCursor_IBActionAttr = C.CXCursor_IBActionAttr,
        CXCursor_IBOutletAttr = C.CXCursor_IBOutletAttr,
        CXCursor_IBOutletCollectionAttr = C.CXCursor_IBOutletCollectionAttr,
        CXCursor_CXXFinalAttr = C.CXCursor_CXXFinalAttr,
        CXCursor_CXXOverrideAttr = C.CXCursor_CXXOverrideAttr,
        CXCursor_AnnotateAttr = C.CXCursor_AnnotateAttr,
        CXCursor_AsmLabelAttr = C.CXCursor_AsmLabelAttr,
        CXCursor_PackedAttr = C.CXCursor_PackedAttr,
        CXCursor_PureAttr = C.CXCursor_PureAttr,
        CXCursor_ConstAttr = C.CXCursor_ConstAttr,
        CXCursor_NoDuplicateAttr = C.CXCursor_NoDuplicateAttr,
        CXCursor_CUDAConstantAttr = C.CXCursor_CUDAConstantAttr,
        CXCursor_CUDADeviceAttr = C.CXCursor_CUDADeviceAttr,
        CXCursor_CUDAGlobalAttr = C.CXCursor_CUDAGlobalAttr,
        CXCursor_CUDAHostAttr = C.CXCursor_CUDAHostAttr,
        CXCursor_CUDASharedAttr = C.CXCursor_CUDASharedAttr,
        CXCursor_VisibilityAttr = C.CXCursor_VisibilityAttr,
        CXCursor_DLLExport = C.CXCursor_DLLExport,
        CXCursor_DLLImport = C.CXCursor_DLLImport,
        CXCursor_NSReturnsRetained = C.CXCursor_NSReturnsRetained,
        CXCursor_NSReturnsNotRetained = C.CXCursor_NSReturnsNotRetained,
        CXCursor_NSReturnsAutoreleased = C.CXCursor_NSReturnsAutoreleased,
        CXCursor_NSConsumesSelf = C.CXCursor_NSConsumesSelf,
        CXCursor_NSConsumed = C.CXCursor_NSConsumed,
        CXCursor_ObjCException = C.CXCursor_ObjCException,
        CXCursor_ObjCNSObject = C.CXCursor_ObjCNSObject,
        CXCursor_ObjCIndependentClass = C.CXCursor_ObjCIndependentClass,
        CXCursor_ObjCPreciseLifetime = C.CXCursor_ObjCPreciseLifetime,
        CXCursor_ObjCReturnsInnerPointer = C.CXCursor_ObjCReturnsInnerPointer,
        CXCursor_ObjCRequiresSuper = C.CXCursor_ObjCRequiresSuper,
        CXCursor_ObjCRootClass = C.CXCursor_ObjCRootClass,
        CXCursor_ObjCSubclassingRestricted = C.CXCursor_ObjCSubclassingRestricted,
        CXCursor_ObjCExplicitProtocolImpl = C.CXCursor_ObjCExplicitProtocolImpl,
        CXCursor_ObjCDesignatedInitializer = C.CXCursor_ObjCDesignatedInitializer,
        CXCursor_ObjCRuntimeVisible = C.CXCursor_ObjCRuntimeVisible,
        CXCursor_ObjCBoxable = C.CXCursor_ObjCBoxable,
        CXCursor_FlagEnum = C.CXCursor_FlagEnum,
        CXCursor_ConvergentAttr = C.CXCursor_ConvergentAttr,
        CXCursor_WarnUnusedAttr = C.CXCursor_WarnUnusedAttr,
        CXCursor_WarnUnusedResultAttr = C.CXCursor_WarnUnusedResultAttr,
        CXCursor_AlignedAttr = C.CXCursor_AlignedAttr,
        CXCursor_LastAttr = C.CXCursor_LastAttr,
        CXCursor_PreprocessingDirective = C.CXCursor_PreprocessingDirective,
        CXCursor_MacroDefinition = C.CXCursor_MacroDefinition,
        CXCursor_MacroExpansion = C.CXCursor_MacroExpansion,
        CXCursor_MacroInstantiation = C.CXCursor_MacroInstantiation,
        CXCursor_InclusionDirective = C.CXCursor_InclusionDirective,
        CXCursor_FirstPreprocessing = C.CXCursor_FirstPreprocessing,
        CXCursor_LastPreprocessing = C.CXCursor_LastPreprocessing,
        CXCursor_ModuleImportDecl = C.CXCursor_ModuleImportDecl,
        CXCursor_TypeAliasTemplateDecl = C.CXCursor_TypeAliasTemplateDecl,
        CXCursor_StaticAssert = C.CXCursor_StaticAssert,
        CXCursor_FriendDecl = C.CXCursor_FriendDecl,
        CXCursor_FirstExtraDecl = C.CXCursor_FirstExtraDecl,
        CXCursor_LastExtraDecl = C.CXCursor_LastExtraDecl,
        CXCursor_OverloadCandidate = C.CXCursor_OverloadCandidate,
    },
    CXLinkageKind = {
        CXLinkage_Invalid = C.CXLinkage_Invalid,
        CXLinkage_NoLinkage = C.CXLinkage_NoLinkage,
        CXLinkage_Internal = C.CXLinkage_Internal,
        CXLinkage_UniqueExternal = C.CXLinkage_UniqueExternal,
        CXLinkage_External = C.CXLinkage_External,
    },
    CXVisibilityKind = {
        CXVisibility_Invalid = C.CXVisibility_Invalid,
        CXVisibility_Hidden = C.CXVisibility_Hidden,
        CXVisibility_Protected = C.CXVisibility_Protected,
        CXVisibility_Default = C.CXVisibility_Default,
    },
    CXLanguageKind = {
        CXLanguage_Invalid = C.CXLanguage_Invalid,
        CXLanguage_C = C.CXLanguage_C,
        CXLanguage_ObjC = C.CXLanguage_ObjC,
        CXLanguage_CPlusPlus = C.CXLanguage_CPlusPlus,
    },
    CXTLSKind = {
        CXTLS_None = C.CXTLS_None,
        CXTLS_Dynamic = C.CXTLS_Dynamic,
        CXTLS_Static = C.CXTLS_Static,
    },
    CXTypeKind = {
        CXType_Invalid = C.CXType_Invalid,
        CXType_Unexposed = C.CXType_Unexposed,
        CXType_Void = C.CXType_Void,
        CXType_Bool = C.CXType_Bool,
        CXType_Char_U = C.CXType_Char_U,
        CXType_UChar = C.CXType_UChar,
        CXType_Char16 = C.CXType_Char16,
        CXType_Char32 = C.CXType_Char32,
        CXType_UShort = C.CXType_UShort,
        CXType_UInt = C.CXType_UInt,
        CXType_ULong = C.CXType_ULong,
        CXType_ULongLong = C.CXType_ULongLong,
        CXType_UInt128 = C.CXType_UInt128,
        CXType_Char_S = C.CXType_Char_S,
        CXType_SChar = C.CXType_SChar,
        CXType_WChar = C.CXType_WChar,
        CXType_Short = C.CXType_Short,
        CXType_Int = C.CXType_Int,
        CXType_Long = C.CXType_Long,
        CXType_LongLong = C.CXType_LongLong,
        CXType_Int128 = C.CXType_Int128,
        CXType_Float = C.CXType_Float,
        CXType_Double = C.CXType_Double,
        CXType_LongDouble = C.CXType_LongDouble,
        CXType_NullPtr = C.CXType_NullPtr,
        CXType_Overload = C.CXType_Overload,
        CXType_Dependent = C.CXType_Dependent,
        CXType_ObjCId = C.CXType_ObjCId,
        CXType_ObjCClass = C.CXType_ObjCClass,
        CXType_ObjCSel = C.CXType_ObjCSel,
        CXType_Float128 = C.CXType_Float128,
        CXType_Half = C.CXType_Half,
        CXType_Float16 = C.CXType_Float16,
        CXType_ShortAccum = C.CXType_ShortAccum,
        CXType_Accum = C.CXType_Accum,
        CXType_LongAccum = C.CXType_LongAccum,
        CXType_UShortAccum = C.CXType_UShortAccum,
        CXType_UAccum = C.CXType_UAccum,
        CXType_ULongAccum = C.CXType_ULongAccum,
        CXType_BFloat16 = C.CXType_BFloat16,
        CXType_FirstBuiltin = C.CXType_FirstBuiltin,
        CXType_LastBuiltin = C.CXType_LastBuiltin,
        CXType_Complex = C.CXType_Complex,
        CXType_Pointer = C.CXType_Pointer,
        CXType_BlockPointer = C.CXType_BlockPointer,
        CXType_LValueReference = C.CXType_LValueReference,
        CXType_RValueReference = C.CXType_RValueReference,
        CXType_Record = C.CXType_Record,
        CXType_Enum = C.CXType_Enum,
        CXType_Typedef = C.CXType_Typedef,
        CXType_ObjCInterface = C.CXType_ObjCInterface,
        CXType_ObjCObjectPointer = C.CXType_ObjCObjectPointer,
        CXType_FunctionNoProto = C.CXType_FunctionNoProto,
        CXType_FunctionProto = C.CXType_FunctionProto,
        CXType_ConstantArray = C.CXType_ConstantArray,
        CXType_Vector = C.CXType_Vector,
        CXType_IncompleteArray = C.CXType_IncompleteArray,
        CXType_VariableArray = C.CXType_VariableArray,
        CXType_DependentSizedArray = C.CXType_DependentSizedArray,
        CXType_MemberPointer = C.CXType_MemberPointer,
        CXType_Auto = C.CXType_Auto,
        CXType_Elaborated = C.CXType_Elaborated,
        CXType_Pipe = C.CXType_Pipe,
        CXType_OCLImage1dRO = C.CXType_OCLImage1dRO,
        CXType_OCLImage1dArrayRO = C.CXType_OCLImage1dArrayRO,
        CXType_OCLImage1dBufferRO = C.CXType_OCLImage1dBufferRO,
        CXType_OCLImage2dRO = C.CXType_OCLImage2dRO,
        CXType_OCLImage2dArrayRO = C.CXType_OCLImage2dArrayRO,
        CXType_OCLImage2dDepthRO = C.CXType_OCLImage2dDepthRO,
        CXType_OCLImage2dArrayDepthRO = C.CXType_OCLImage2dArrayDepthRO,
        CXType_OCLImage2dMSAARO = C.CXType_OCLImage2dMSAARO,
        CXType_OCLImage2dArrayMSAARO = C.CXType_OCLImage2dArrayMSAARO,
        CXType_OCLImage2dMSAADepthRO = C.CXType_OCLImage2dMSAADepthRO,
        CXType_OCLImage2dArrayMSAADepthRO = C.CXType_OCLImage2dArrayMSAADepthRO,
        CXType_OCLImage3dRO = C.CXType_OCLImage3dRO,
        CXType_OCLImage1dWO = C.CXType_OCLImage1dWO,
        CXType_OCLImage1dArrayWO = C.CXType_OCLImage1dArrayWO,
        CXType_OCLImage1dBufferWO = C.CXType_OCLImage1dBufferWO,
        CXType_OCLImage2dWO = C.CXType_OCLImage2dWO,
        CXType_OCLImage2dArrayWO = C.CXType_OCLImage2dArrayWO,
        CXType_OCLImage2dDepthWO = C.CXType_OCLImage2dDepthWO,
        CXType_OCLImage2dArrayDepthWO = C.CXType_OCLImage2dArrayDepthWO,
        CXType_OCLImage2dMSAAWO = C.CXType_OCLImage2dMSAAWO,
        CXType_OCLImage2dArrayMSAAWO = C.CXType_OCLImage2dArrayMSAAWO,
        CXType_OCLImage2dMSAADepthWO = C.CXType_OCLImage2dMSAADepthWO,
        CXType_OCLImage2dArrayMSAADepthWO = C.CXType_OCLImage2dArrayMSAADepthWO,
        CXType_OCLImage3dWO = C.CXType_OCLImage3dWO,
        CXType_OCLImage1dRW = C.CXType_OCLImage1dRW,
        CXType_OCLImage1dArrayRW = C.CXType_OCLImage1dArrayRW,
        CXType_OCLImage1dBufferRW = C.CXType_OCLImage1dBufferRW,
        CXType_OCLImage2dRW = C.CXType_OCLImage2dRW,
        CXType_OCLImage2dArrayRW = C.CXType_OCLImage2dArrayRW,
        CXType_OCLImage2dDepthRW = C.CXType_OCLImage2dDepthRW,
        CXType_OCLImage2dArrayDepthRW = C.CXType_OCLImage2dArrayDepthRW,
        CXType_OCLImage2dMSAARW = C.CXType_OCLImage2dMSAARW,
        CXType_OCLImage2dArrayMSAARW = C.CXType_OCLImage2dArrayMSAARW,
        CXType_OCLImage2dMSAADepthRW = C.CXType_OCLImage2dMSAADepthRW,
        CXType_OCLImage2dArrayMSAADepthRW = C.CXType_OCLImage2dArrayMSAADepthRW,
        CXType_OCLImage3dRW = C.CXType_OCLImage3dRW,
        CXType_OCLSampler = C.CXType_OCLSampler,
        CXType_OCLEvent = C.CXType_OCLEvent,
        CXType_OCLQueue = C.CXType_OCLQueue,
        CXType_OCLReserveID = C.CXType_OCLReserveID,
        CXType_ObjCObject = C.CXType_ObjCObject,
        CXType_ObjCTypeParam = C.CXType_ObjCTypeParam,
        CXType_Attributed = C.CXType_Attributed,
        CXType_OCLIntelSubgroupAVCMcePayload = C.CXType_OCLIntelSubgroupAVCMcePayload,
        CXType_OCLIntelSubgroupAVCImePayload = C.CXType_OCLIntelSubgroupAVCImePayload,
        CXType_OCLIntelSubgroupAVCRefPayload = C.CXType_OCLIntelSubgroupAVCRefPayload,
        CXType_OCLIntelSubgroupAVCSicPayload = C.CXType_OCLIntelSubgroupAVCSicPayload,
        CXType_OCLIntelSubgroupAVCMceResult = C.CXType_OCLIntelSubgroupAVCMceResult,
        CXType_OCLIntelSubgroupAVCImeResult = C.CXType_OCLIntelSubgroupAVCImeResult,
        CXType_OCLIntelSubgroupAVCRefResult = C.CXType_OCLIntelSubgroupAVCRefResult,
        CXType_OCLIntelSubgroupAVCSicResult = C.CXType_OCLIntelSubgroupAVCSicResult,
        CXType_OCLIntelSubgroupAVCImeResultSingleRefStreamout = C.CXType_OCLIntelSubgroupAVCImeResultSingleRefStreamout,
        CXType_OCLIntelSubgroupAVCImeResultDualRefStreamout = C.CXType_OCLIntelSubgroupAVCImeResultDualRefStreamout,
        CXType_OCLIntelSubgroupAVCImeSingleRefStreamin = C.CXType_OCLIntelSubgroupAVCImeSingleRefStreamin,
        CXType_OCLIntelSubgroupAVCImeDualRefStreamin = C.CXType_OCLIntelSubgroupAVCImeDualRefStreamin,
        CXType_ExtVector = C.CXType_ExtVector,
        CXType_Atomic = C.CXType_Atomic,
    },
    CXCallingConv = {
        CXCallingConv_Default = C.CXCallingConv_Default,
        CXCallingConv_C = C.CXCallingConv_C,
        CXCallingConv_X86StdCall = C.CXCallingConv_X86StdCall,
        CXCallingConv_X86FastCall = C.CXCallingConv_X86FastCall,
        CXCallingConv_X86ThisCall = C.CXCallingConv_X86ThisCall,
        CXCallingConv_X86Pascal = C.CXCallingConv_X86Pascal,
        CXCallingConv_AAPCS = C.CXCallingConv_AAPCS,
        CXCallingConv_AAPCS_VFP = C.CXCallingConv_AAPCS_VFP,
        CXCallingConv_X86RegCall = C.CXCallingConv_X86RegCall,
        CXCallingConv_IntelOclBicc = C.CXCallingConv_IntelOclBicc,
        CXCallingConv_Win64 = C.CXCallingConv_Win64,
        CXCallingConv_X86_64Win64 = C.CXCallingConv_X86_64Win64,
        CXCallingConv_X86_64SysV = C.CXCallingConv_X86_64SysV,
        CXCallingConv_X86VectorCall = C.CXCallingConv_X86VectorCall,
        CXCallingConv_Swift = C.CXCallingConv_Swift,
        CXCallingConv_PreserveMost = C.CXCallingConv_PreserveMost,
        CXCallingConv_PreserveAll = C.CXCallingConv_PreserveAll,
        CXCallingConv_AArch64VectorCall = C.CXCallingConv_AArch64VectorCall,
        CXCallingConv_Invalid = C.CXCallingConv_Invalid,
        CXCallingConv_Unexposed = C.CXCallingConv_Unexposed,
    },
    CXTemplateArgumentKind = {
        CXTemplateArgumentKind_Null = C.CXTemplateArgumentKind_Null,
        CXTemplateArgumentKind_Type = C.CXTemplateArgumentKind_Type,
        CXTemplateArgumentKind_Declaration = C.CXTemplateArgumentKind_Declaration,
        CXTemplateArgumentKind_NullPtr = C.CXTemplateArgumentKind_NullPtr,
        CXTemplateArgumentKind_Integral = C.CXTemplateArgumentKind_Integral,
        CXTemplateArgumentKind_Template = C.CXTemplateArgumentKind_Template,
        CXTemplateArgumentKind_TemplateExpansion = C.CXTemplateArgumentKind_TemplateExpansion,
        CXTemplateArgumentKind_Expression = C.CXTemplateArgumentKind_Expression,
        CXTemplateArgumentKind_Pack = C.CXTemplateArgumentKind_Pack,
        CXTemplateArgumentKind_Invalid = C.CXTemplateArgumentKind_Invalid,
    },
    CXTypeNullabilityKind = {
        CXTypeNullability_NonNull = C.CXTypeNullability_NonNull,
        CXTypeNullability_Nullable = C.CXTypeNullability_Nullable,
        CXTypeNullability_Unspecified = C.CXTypeNullability_Unspecified,
        CXTypeNullability_Invalid = C.CXTypeNullability_Invalid,
    },
    CXTypeLayoutError = {
        CXTypeLayoutError_Invalid = C.CXTypeLayoutError_Invalid,
        CXTypeLayoutError_Incomplete = C.CXTypeLayoutError_Incomplete,
        CXTypeLayoutError_Dependent = C.CXTypeLayoutError_Dependent,
        CXTypeLayoutError_NotConstantSize = C.CXTypeLayoutError_NotConstantSize,
        CXTypeLayoutError_InvalidFieldName = C.CXTypeLayoutError_InvalidFieldName,
        CXTypeLayoutError_Undeduced = C.CXTypeLayoutError_Undeduced,
    },
    CXRefQualifierKind = {
        CXRefQualifier_None = C.CXRefQualifier_None,
        CXRefQualifier_LValue = C.CXRefQualifier_LValue,
        CXRefQualifier_RValue = C.CXRefQualifier_RValue,
    },
    CX_CXXAccessSpecifier = {
        CX_CXXInvalidAccessSpecifier = C.CX_CXXInvalidAccessSpecifier,
        CX_CXXPublic = C.CX_CXXPublic,
        CX_CXXProtected = C.CX_CXXProtected,
        CX_CXXPrivate = C.CX_CXXPrivate,
    },
    CX_StorageClass = {
        CX_SC_Invalid = C.CX_SC_Invalid,
        CX_SC_None = C.CX_SC_None,
        CX_SC_Extern = C.CX_SC_Extern,
        CX_SC_Static = C.CX_SC_Static,
        CX_SC_PrivateExtern = C.CX_SC_PrivateExtern,
        CX_SC_OpenCLWorkGroupLocal = C.CX_SC_OpenCLWorkGroupLocal,
        CX_SC_Auto = C.CX_SC_Auto,
        CX_SC_Register = C.CX_SC_Register,
    },
    CXChildVisitResult = {
        CXChildVisit_Break = C.CXChildVisit_Break,
        CXChildVisit_Continue = C.CXChildVisit_Continue,
        CXChildVisit_Recurse = C.CXChildVisit_Recurse,
    },
    CXPrintingPolicyProperty = {
        CXPrintingPolicy_Indentation = C.CXPrintingPolicy_Indentation,
        CXPrintingPolicy_SuppressSpecifiers = C.CXPrintingPolicy_SuppressSpecifiers,
        CXPrintingPolicy_SuppressTagKeyword = C.CXPrintingPolicy_SuppressTagKeyword,
        CXPrintingPolicy_IncludeTagDefinition = C.CXPrintingPolicy_IncludeTagDefinition,
        CXPrintingPolicy_SuppressScope = C.CXPrintingPolicy_SuppressScope,
        CXPrintingPolicy_SuppressUnwrittenScope = C.CXPrintingPolicy_SuppressUnwrittenScope,
        CXPrintingPolicy_SuppressInitializers = C.CXPrintingPolicy_SuppressInitializers,
        CXPrintingPolicy_ConstantArraySizeAsWritten = C.CXPrintingPolicy_ConstantArraySizeAsWritten,
        CXPrintingPolicy_AnonymousTagLocations = C.CXPrintingPolicy_AnonymousTagLocations,
        CXPrintingPolicy_SuppressStrongLifetime = C.CXPrintingPolicy_SuppressStrongLifetime,
        CXPrintingPolicy_SuppressLifetimeQualifiers = C.CXPrintingPolicy_SuppressLifetimeQualifiers,
        CXPrintingPolicy_SuppressTemplateArgsInCXXConstructors = C.CXPrintingPolicy_SuppressTemplateArgsInCXXConstructors,
        CXPrintingPolicy_Bool = C.CXPrintingPolicy_Bool,
        CXPrintingPolicy_Restrict = C.CXPrintingPolicy_Restrict,
        CXPrintingPolicy_Alignof = C.CXPrintingPolicy_Alignof,
        CXPrintingPolicy_UnderscoreAlignof = C.CXPrintingPolicy_UnderscoreAlignof,
        CXPrintingPolicy_UseVoidForZeroParams = C.CXPrintingPolicy_UseVoidForZeroParams,
        CXPrintingPolicy_TerseOutput = C.CXPrintingPolicy_TerseOutput,
        CXPrintingPolicy_PolishForDeclaration = C.CXPrintingPolicy_PolishForDeclaration,
        CXPrintingPolicy_Half = C.CXPrintingPolicy_Half,
        CXPrintingPolicy_MSWChar = C.CXPrintingPolicy_MSWChar,
        CXPrintingPolicy_IncludeNewlines = C.CXPrintingPolicy_IncludeNewlines,
        CXPrintingPolicy_MSVCFormatting = C.CXPrintingPolicy_MSVCFormatting,
        CXPrintingPolicy_ConstantsAsWritten = C.CXPrintingPolicy_ConstantsAsWritten,
        CXPrintingPolicy_SuppressImplicitBase = C.CXPrintingPolicy_SuppressImplicitBase,
        CXPrintingPolicy_FullyQualifiedName = C.CXPrintingPolicy_FullyQualifiedName,
        CXPrintingPolicy_LastProperty = C.CXPrintingPolicy_LastProperty,
    },
    CXNameRefFlags = {
        CXNameRange_WantQualifier = C.CXNameRange_WantQualifier,
        CXNameRange_WantTemplateArgs = C.CXNameRange_WantTemplateArgs,
        CXNameRange_WantSinglePiece = C.CXNameRange_WantSinglePiece,
    },
    CXTokenKind = {
        CXToken_Punctuation = C.CXToken_Punctuation,
        CXToken_Keyword = C.CXToken_Keyword,
        CXToken_Identifier = C.CXToken_Identifier,
        CXToken_Literal = C.CXToken_Literal,
        CXToken_Comment = C.CXToken_Comment,
    },
    CXCompletionChunkKind = {
        CXCompletionChunk_Optional = C.CXCompletionChunk_Optional,
        CXCompletionChunk_TypedText = C.CXCompletionChunk_TypedText,
        CXCompletionChunk_Text = C.CXCompletionChunk_Text,
        CXCompletionChunk_Placeholder = C.CXCompletionChunk_Placeholder,
        CXCompletionChunk_Informative = C.CXCompletionChunk_Informative,
        CXCompletionChunk_CurrentParameter = C.CXCompletionChunk_CurrentParameter,
        CXCompletionChunk_LeftParen = C.CXCompletionChunk_LeftParen,
        CXCompletionChunk_RightParen = C.CXCompletionChunk_RightParen,
        CXCompletionChunk_LeftBracket = C.CXCompletionChunk_LeftBracket,
        CXCompletionChunk_RightBracket = C.CXCompletionChunk_RightBracket,
        CXCompletionChunk_LeftBrace = C.CXCompletionChunk_LeftBrace,
        CXCompletionChunk_RightBrace = C.CXCompletionChunk_RightBrace,
        CXCompletionChunk_LeftAngle = C.CXCompletionChunk_LeftAngle,
        CXCompletionChunk_RightAngle = C.CXCompletionChunk_RightAngle,
        CXCompletionChunk_Comma = C.CXCompletionChunk_Comma,
        CXCompletionChunk_ResultType = C.CXCompletionChunk_ResultType,
        CXCompletionChunk_Colon = C.CXCompletionChunk_Colon,
        CXCompletionChunk_SemiColon = C.CXCompletionChunk_SemiColon,
        CXCompletionChunk_Equal = C.CXCompletionChunk_Equal,
        CXCompletionChunk_HorizontalSpace = C.CXCompletionChunk_HorizontalSpace,
        CXCompletionChunk_VerticalSpace = C.CXCompletionChunk_VerticalSpace,
    },
    CXCodeComplete_Flags = {
        CXCodeComplete_IncludeMacros = C.CXCodeComplete_IncludeMacros,
        CXCodeComplete_IncludeCodePatterns = C.CXCodeComplete_IncludeCodePatterns,
        CXCodeComplete_IncludeBriefComments = C.CXCodeComplete_IncludeBriefComments,
        CXCodeComplete_SkipPreamble = C.CXCodeComplete_SkipPreamble,
        CXCodeComplete_IncludeCompletionsWithFixIts = C.CXCodeComplete_IncludeCompletionsWithFixIts,
    },
    CXCompletionContext = {
        CXCompletionContext_Unexposed = C.CXCompletionContext_Unexposed,
        CXCompletionContext_AnyType = C.CXCompletionContext_AnyType,
        CXCompletionContext_AnyValue = C.CXCompletionContext_AnyValue,
        CXCompletionContext_ObjCObjectValue = C.CXCompletionContext_ObjCObjectValue,
        CXCompletionContext_ObjCSelectorValue = C.CXCompletionContext_ObjCSelectorValue,
        CXCompletionContext_CXXClassTypeValue = C.CXCompletionContext_CXXClassTypeValue,
        CXCompletionContext_DotMemberAccess = C.CXCompletionContext_DotMemberAccess,
        CXCompletionContext_ArrowMemberAccess = C.CXCompletionContext_ArrowMemberAccess,
        CXCompletionContext_ObjCPropertyAccess = C.CXCompletionContext_ObjCPropertyAccess,
        CXCompletionContext_EnumTag = C.CXCompletionContext_EnumTag,
        CXCompletionContext_UnionTag = C.CXCompletionContext_UnionTag,
        CXCompletionContext_StructTag = C.CXCompletionContext_StructTag,
        CXCompletionContext_ClassTag = C.CXCompletionContext_ClassTag,
        CXCompletionContext_Namespace = C.CXCompletionContext_Namespace,
        CXCompletionContext_NestedNameSpecifier = C.CXCompletionContext_NestedNameSpecifier,
        CXCompletionContext_ObjCInterface = C.CXCompletionContext_ObjCInterface,
        CXCompletionContext_ObjCProtocol = C.CXCompletionContext_ObjCProtocol,
        CXCompletionContext_ObjCCategory = C.CXCompletionContext_ObjCCategory,
        CXCompletionContext_ObjCInstanceMessage = C.CXCompletionContext_ObjCInstanceMessage,
        CXCompletionContext_ObjCClassMessage = C.CXCompletionContext_ObjCClassMessage,
        CXCompletionContext_ObjCSelectorName = C.CXCompletionContext_ObjCSelectorName,
        CXCompletionContext_MacroName = C.CXCompletionContext_MacroName,
        CXCompletionContext_NaturalLanguage = C.CXCompletionContext_NaturalLanguage,
        CXCompletionContext_IncludedFile = C.CXCompletionContext_IncludedFile,
        CXCompletionContext_Unknown = C.CXCompletionContext_Unknown,
    },
    CXVisitorResult = {
        CXVisit_Break = C.CXVisit_Break,
        CXVisit_Continue = C.CXVisit_Continue,
    },
    CXErrorCode = {
        CXError_Success = C.CXError_Success,
        CXError_Failure = C.CXError_Failure,
        CXError_Crashed = C.CXError_Crashed,
        CXError_InvalidArguments = C.CXError_InvalidArguments,
        CXError_ASTReadError = C.CXError_ASTReadError,
    },
}
---@class __time64_t
---@class time_t
---@class size_t
---@class CXIndex
---@class CXFile
---@class CXFileUniqueID
---@class CXTranslationUnitImpl
---@class CXTranslationUnit
---@class CXSourceLocation
---@class CXSourceRange
---@class CXSourceRangeList
---@class CXDiagnosticSet
---@class CXDiagnostic
---@class CXUnsavedFile
---@class CXTUResourceUsageEntry
---@class CXTUResourceUsage
---@class CXTargetInfoImpl
---@class CXTargetInfo
---@class CXCursor
---@class CXVersion
---@class CXPlatformAvailability
---@class CXCursorSetImpl
---@class CXCursorSet
---@class CXType
---@class CXClientData
---@class CXCursorVisitor
---@class CXPrintingPolicy
---@class CXModule
---@class CXToken
---@class CXCompletionString
---@class CXCompletionResult
---@class CXCodeCompleteResults
---@class CXInclusionVisitor
---@class CXEvalResult
---@class CXEvalResultKind
---@class CXRemapping
---@class CXResult
---@class CXCursorAndRangeVisitor
---@class CXIdxEntityKind
---@class CXIdxEntityCXXTemplateKind
---@class CXIdxEntityLanguage
---@class CXIdxAttrKind
---@class CXIdxLoc
---@class CXIdxAttrInfo
---@class CXIdxEntityInfo
---@class CXIdxContainerInfo
---@class CXIdxDeclInfo
---@class CXIdxObjCContainerKind
---@class CXIdxObjCContainerDeclInfo
---@class CXIdxBaseClassInfo
---@class CXIdxObjCProtocolRefInfo
---@class CXIdxObjCProtocolRefListInfo
---@class CXIdxObjCInterfaceDeclInfo
---@class CXIdxObjCCategoryDeclInfo
---@class CXIdxObjCPropertyDeclInfo
---@class CXIdxIBOutletCollectionAttrInfo
---@class CXIdxCXXClassDeclInfo
---@class CXIdxClientContainer
---@class CXIdxClientEntity
---@class CXIndexAction
---@class CXIdxClientFile
---@class CXIdxIncludedFileInfo
---@class CXIdxClientASTFile
---@class CXIdxImportedASTFileInfo
---@class CXIdxEntityRefKind
---@class CXSymbolRole
---@class CXIdxEntityRefInfo
---@class IndexerCallbacks
---@class CXFieldVisitor
---@class CXString
---@class CXStringSet
-----------------------------------------------------------------------------
-- libclang.dll
-----------------------------------------------------------------------------
---@type Table<string, any>
local clang = ffi.load('libclang')
M.cache.clang = clang
M.libs.clang = {
    ---@type fun(excludeDeclarationsFromPCH:integer, displayDiagnostics:integer):CXIndex
    clang_createIndex = clang.clang_createIndex,
    ---@type fun(index:CXIndex):nil
    clang_disposeIndex = clang.clang_disposeIndex,
    ---@type fun(param1:CXIndex, options:integer):nil
    clang_CXIndex_setGlobalOptions = clang.clang_CXIndex_setGlobalOptions,
    ---@type fun(param1:CXIndex):integer
    clang_CXIndex_getGlobalOptions = clang.clang_CXIndex_getGlobalOptions,
    ---@type fun(param1:CXIndex, Path:string):nil
    clang_CXIndex_setInvocationEmissionPathOption = clang.clang_CXIndex_setInvocationEmissionPathOption,
    ---@type fun(SFile:CXFile):CXString
    clang_getFileName = clang.clang_getFileName,
    ---@type fun(SFile:CXFile):time_t
    clang_getFileTime = clang.clang_getFileTime,
    ---@type fun(file:CXFile, outID:any):integer
    clang_getFileUniqueID = clang.clang_getFileUniqueID,
    ---@type fun(tu:CXTranslationUnit, file:CXFile):integer
    clang_isFileMultipleIncludeGuarded = clang.clang_isFileMultipleIncludeGuarded,
    ---@type fun(tu:CXTranslationUnit, file_name:string):CXFile
    clang_getFile = clang.clang_getFile,
    ---@type fun(tu:CXTranslationUnit, file:CXFile, size:any):string
    clang_getFileContents = clang.clang_getFileContents,
    ---@type fun(file1:CXFile, file2:CXFile):integer
    clang_File_isEqual = clang.clang_File_isEqual,
    ---@type fun(file:CXFile):CXString
    clang_File_tryGetRealPathName = clang.clang_File_tryGetRealPathName,
    ---@type fun():CXSourceLocation
    clang_getNullLocation = clang.clang_getNullLocation,
    ---@type fun(loc1:CXSourceLocation, loc2:CXSourceLocation):integer
    clang_equalLocations = clang.clang_equalLocations,
    ---@type fun(tu:CXTranslationUnit, file:CXFile, line:integer, column:integer):CXSourceLocation
    clang_getLocation = clang.clang_getLocation,
    ---@type fun(tu:CXTranslationUnit, file:CXFile, offset:integer):CXSourceLocation
    clang_getLocationForOffset = clang.clang_getLocationForOffset,
    ---@type fun(location:CXSourceLocation):integer
    clang_Location_isInSystemHeader = clang.clang_Location_isInSystemHeader,
    ---@type fun(location:CXSourceLocation):integer
    clang_Location_isFromMainFile = clang.clang_Location_isFromMainFile,
    ---@type fun():CXSourceRange
    clang_getNullRange = clang.clang_getNullRange,
    ---@type fun(begin:CXSourceLocation, end_:CXSourceLocation):CXSourceRange
    clang_getRange = clang.clang_getRange,
    ---@type fun(range1:CXSourceRange, range2:CXSourceRange):integer
    clang_equalRanges = clang.clang_equalRanges,
    ---@type fun(range:CXSourceRange):integer
    clang_Range_isNull = clang.clang_Range_isNull,
    ---@type fun(location:CXSourceLocation, file:any, line:any, column:any, offset:any):nil
    clang_getExpansionLocation = clang.clang_getExpansionLocation,
    ---@type fun(location:CXSourceLocation, filename:any, line:any, column:any):nil
    clang_getPresumedLocation = clang.clang_getPresumedLocation,
    ---@type fun(location:CXSourceLocation, file:any, line:any, column:any, offset:any):nil
    clang_getInstantiationLocation = clang.clang_getInstantiationLocation,
    ---@type fun(location:CXSourceLocation, file:any, line:any, column:any, offset:any):nil
    clang_getSpellingLocation = clang.clang_getSpellingLocation,
    ---@type fun(location:CXSourceLocation, file:any, line:any, column:any, offset:any):nil
    clang_getFileLocation = clang.clang_getFileLocation,
    ---@type fun(range:CXSourceRange):CXSourceLocation
    clang_getRangeStart = clang.clang_getRangeStart,
    ---@type fun(range:CXSourceRange):CXSourceLocation
    clang_getRangeEnd = clang.clang_getRangeEnd,
    ---@type fun(tu:CXTranslationUnit, file:CXFile):any
    clang_getSkippedRanges = clang.clang_getSkippedRanges,
    ---@type fun(tu:CXTranslationUnit):any
    clang_getAllSkippedRanges = clang.clang_getAllSkippedRanges,
    ---@type fun(ranges:any):nil
    clang_disposeSourceRangeList = clang.clang_disposeSourceRangeList,
    ---@type fun(Diags:CXDiagnosticSet):integer
    clang_getNumDiagnosticsInSet = clang.clang_getNumDiagnosticsInSet,
    ---@type fun(Diags:CXDiagnosticSet, Index:integer):CXDiagnostic
    clang_getDiagnosticInSet = clang.clang_getDiagnosticInSet,
    ---@type fun(file:string, error:any, errorString:any):CXDiagnosticSet
    clang_loadDiagnostics = clang.clang_loadDiagnostics,
    ---@type fun(Diags:CXDiagnosticSet):nil
    clang_disposeDiagnosticSet = clang.clang_disposeDiagnosticSet,
    ---@type fun(D:CXDiagnostic):CXDiagnosticSet
    clang_getChildDiagnostics = clang.clang_getChildDiagnostics,
    ---@type fun(Unit:CXTranslationUnit):integer
    clang_getNumDiagnostics = clang.clang_getNumDiagnostics,
    ---@type fun(Unit:CXTranslationUnit, Index:integer):CXDiagnostic
    clang_getDiagnostic = clang.clang_getDiagnostic,
    ---@type fun(Unit:CXTranslationUnit):CXDiagnosticSet
    clang_getDiagnosticSetFromTU = clang.clang_getDiagnosticSetFromTU,
    ---@type fun(Diagnostic:CXDiagnostic):nil
    clang_disposeDiagnostic = clang.clang_disposeDiagnostic,
    ---@type fun(Diagnostic:CXDiagnostic, Options:integer):CXString
    clang_formatDiagnostic = clang.clang_formatDiagnostic,
    ---@type fun():integer
    clang_defaultDiagnosticDisplayOptions = clang.clang_defaultDiagnosticDisplayOptions,
    ---@type fun(param1:CXDiagnostic):integer
    clang_getDiagnosticSeverity = clang.clang_getDiagnosticSeverity,
    ---@type fun(param1:CXDiagnostic):CXSourceLocation
    clang_getDiagnosticLocation = clang.clang_getDiagnosticLocation,
    ---@type fun(param1:CXDiagnostic):CXString
    clang_getDiagnosticSpelling = clang.clang_getDiagnosticSpelling,
    ---@type fun(Diag:CXDiagnostic, Disable:any):CXString
    clang_getDiagnosticOption = clang.clang_getDiagnosticOption,
    ---@type fun(param1:CXDiagnostic):integer
    clang_getDiagnosticCategory = clang.clang_getDiagnosticCategory,
    ---@type fun(Category:integer):CXString
    clang_getDiagnosticCategoryName = clang.clang_getDiagnosticCategoryName,
    ---@type fun(param1:CXDiagnostic):CXString
    clang_getDiagnosticCategoryText = clang.clang_getDiagnosticCategoryText,
    ---@type fun(param1:CXDiagnostic):integer
    clang_getDiagnosticNumRanges = clang.clang_getDiagnosticNumRanges,
    ---@type fun(Diagnostic:CXDiagnostic, Range:integer):CXSourceRange
    clang_getDiagnosticRange = clang.clang_getDiagnosticRange,
    ---@type fun(Diagnostic:CXDiagnostic):integer
    clang_getDiagnosticNumFixIts = clang.clang_getDiagnosticNumFixIts,
    ---@type fun(Diagnostic:CXDiagnostic, FixIt:integer, ReplacementRange:any):CXString
    clang_getDiagnosticFixIt = clang.clang_getDiagnosticFixIt,
    ---@type fun(CTUnit:CXTranslationUnit):CXString
    clang_getTranslationUnitSpelling = clang.clang_getTranslationUnitSpelling,
    ---@type fun(CIdx:CXIndex, source_filename:string, num_clang_command_line_args:integer, clang_command_line_args:any, num_unsaved_files:integer, unsaved_files:any):CXTranslationUnit
    clang_createTranslationUnitFromSourceFile = clang.clang_createTranslationUnitFromSourceFile,
    ---@type fun(CIdx:CXIndex, ast_filename:string):CXTranslationUnit
    clang_createTranslationUnit = clang.clang_createTranslationUnit,
    ---@type fun(CIdx:CXIndex, ast_filename:string, out_TU:any):integer
    clang_createTranslationUnit2 = clang.clang_createTranslationUnit2,
    ---@type fun():integer
    clang_defaultEditingTranslationUnitOptions = clang.clang_defaultEditingTranslationUnitOptions,
    ---@type fun(CIdx:CXIndex, source_filename:string, command_line_args:any, num_command_line_args:integer, unsaved_files:any, num_unsaved_files:integer, options:integer):CXTranslationUnit
    clang_parseTranslationUnit = clang.clang_parseTranslationUnit,
    ---@type fun(CIdx:CXIndex, source_filename:string, command_line_args:any, num_command_line_args:integer, unsaved_files:any, num_unsaved_files:integer, options:integer, out_TU:any):integer
    clang_parseTranslationUnit2 = clang.clang_parseTranslationUnit2,
    ---@type fun(CIdx:CXIndex, source_filename:string, command_line_args:any, num_command_line_args:integer, unsaved_files:any, num_unsaved_files:integer, options:integer, out_TU:any):integer
    clang_parseTranslationUnit2FullArgv = clang.clang_parseTranslationUnit2FullArgv,
    ---@type fun(TU:CXTranslationUnit):integer
    clang_defaultSaveOptions = clang.clang_defaultSaveOptions,
    ---@type fun(TU:CXTranslationUnit, FileName:string, options:integer):integer
    clang_saveTranslationUnit = clang.clang_saveTranslationUnit,
    ---@type fun(param1:CXTranslationUnit):integer
    clang_suspendTranslationUnit = clang.clang_suspendTranslationUnit,
    ---@type fun(param1:CXTranslationUnit):nil
    clang_disposeTranslationUnit = clang.clang_disposeTranslationUnit,
    ---@type fun(TU:CXTranslationUnit):integer
    clang_defaultReparseOptions = clang.clang_defaultReparseOptions,
    ---@type fun(TU:CXTranslationUnit, num_unsaved_files:integer, unsaved_files:any, options:integer):integer
    clang_reparseTranslationUnit = clang.clang_reparseTranslationUnit,
    ---@type fun(kind:integer):string
    clang_getTUResourceUsageName = clang.clang_getTUResourceUsageName,
    ---@type fun(TU:CXTranslationUnit):CXTUResourceUsage
    clang_getCXTUResourceUsage = clang.clang_getCXTUResourceUsage,
    ---@type fun(usage:CXTUResourceUsage):nil
    clang_disposeCXTUResourceUsage = clang.clang_disposeCXTUResourceUsage,
    ---@type fun(CTUnit:CXTranslationUnit):CXTargetInfo
    clang_getTranslationUnitTargetInfo = clang.clang_getTranslationUnitTargetInfo,
    ---@type fun(Info:CXTargetInfo):nil
    clang_TargetInfo_dispose = clang.clang_TargetInfo_dispose,
    ---@type fun(Info:CXTargetInfo):CXString
    clang_TargetInfo_getTriple = clang.clang_TargetInfo_getTriple,
    ---@type fun(Info:CXTargetInfo):integer
    clang_TargetInfo_getPointerWidth = clang.clang_TargetInfo_getPointerWidth,
    ---@type fun():CXCursor
    clang_getNullCursor = clang.clang_getNullCursor,
    ---@type fun(param1:CXTranslationUnit):CXCursor
    clang_getTranslationUnitCursor = clang.clang_getTranslationUnitCursor,
    ---@type fun(param1:CXCursor, param2:CXCursor):integer
    clang_equalCursors = clang.clang_equalCursors,
    ---@type fun(cursor:CXCursor):integer
    clang_Cursor_isNull = clang.clang_Cursor_isNull,
    ---@type fun(param1:CXCursor):integer
    clang_hashCursor = clang.clang_hashCursor,
    ---@type fun(param1:CXCursor):integer
    clang_getCursorKind = clang.clang_getCursorKind,
    ---@type fun(param1:integer):integer
    clang_isDeclaration = clang.clang_isDeclaration,
    ---@type fun(param1:CXCursor):integer
    clang_isInvalidDeclaration = clang.clang_isInvalidDeclaration,
    ---@type fun(param1:integer):integer
    clang_isReference = clang.clang_isReference,
    ---@type fun(param1:integer):integer
    clang_isExpression = clang.clang_isExpression,
    ---@type fun(param1:integer):integer
    clang_isStatement = clang.clang_isStatement,
    ---@type fun(param1:integer):integer
    clang_isAttribute = clang.clang_isAttribute,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_hasAttrs = clang.clang_Cursor_hasAttrs,
    ---@type fun(param1:integer):integer
    clang_isInvalid = clang.clang_isInvalid,
    ---@type fun(param1:integer):integer
    clang_isTranslationUnit = clang.clang_isTranslationUnit,
    ---@type fun(param1:integer):integer
    clang_isPreprocessing = clang.clang_isPreprocessing,
    ---@type fun(param1:integer):integer
    clang_isUnexposed = clang.clang_isUnexposed,
    ---@type fun(cursor:CXCursor):integer
    clang_getCursorLinkage = clang.clang_getCursorLinkage,
    ---@type fun(cursor:CXCursor):integer
    clang_getCursorVisibility = clang.clang_getCursorVisibility,
    ---@type fun(cursor:CXCursor):integer
    clang_getCursorAvailability = clang.clang_getCursorAvailability,
    ---@type fun(cursor:CXCursor, always_deprecated:any, deprecated_message:any, always_unavailable:any, unavailable_message:any, availability:any, availability_size:integer):integer
    clang_getCursorPlatformAvailability = clang.clang_getCursorPlatformAvailability,
    ---@type fun(availability:any):nil
    clang_disposeCXPlatformAvailability = clang.clang_disposeCXPlatformAvailability,
    ---@type fun(cursor:CXCursor):integer
    clang_getCursorLanguage = clang.clang_getCursorLanguage,
    ---@type fun(cursor:CXCursor):integer
    clang_getCursorTLSKind = clang.clang_getCursorTLSKind,
    ---@type fun(param1:CXCursor):CXTranslationUnit
    clang_Cursor_getTranslationUnit = clang.clang_Cursor_getTranslationUnit,
    ---@type fun():CXCursorSet
    clang_createCXCursorSet = clang.clang_createCXCursorSet,
    ---@type fun(cset:CXCursorSet):nil
    clang_disposeCXCursorSet = clang.clang_disposeCXCursorSet,
    ---@type fun(cset:CXCursorSet, cursor:CXCursor):integer
    clang_CXCursorSet_contains = clang.clang_CXCursorSet_contains,
    ---@type fun(cset:CXCursorSet, cursor:CXCursor):integer
    clang_CXCursorSet_insert = clang.clang_CXCursorSet_insert,
    ---@type fun(cursor:CXCursor):CXCursor
    clang_getCursorSemanticParent = clang.clang_getCursorSemanticParent,
    ---@type fun(cursor:CXCursor):CXCursor
    clang_getCursorLexicalParent = clang.clang_getCursorLexicalParent,
    ---@type fun(cursor:CXCursor, overridden:any, num_overridden:any):nil
    clang_getOverriddenCursors = clang.clang_getOverriddenCursors,
    ---@type fun(overridden:any):nil
    clang_disposeOverriddenCursors = clang.clang_disposeOverriddenCursors,
    ---@type fun(cursor:CXCursor):CXFile
    clang_getIncludedFile = clang.clang_getIncludedFile,
    ---@type fun(param1:CXTranslationUnit, param2:CXSourceLocation):CXCursor
    clang_getCursor = clang.clang_getCursor,
    ---@type fun(param1:CXCursor):CXSourceLocation
    clang_getCursorLocation = clang.clang_getCursorLocation,
    ---@type fun(param1:CXCursor):CXSourceRange
    clang_getCursorExtent = clang.clang_getCursorExtent,
    ---@type fun(C:CXCursor):CXType
    clang_getCursorType = clang.clang_getCursorType,
    ---@type fun(CT:CXType):CXString
    clang_getTypeSpelling = clang.clang_getTypeSpelling,
    ---@type fun(C:CXCursor):CXType
    clang_getTypedefDeclUnderlyingType = clang.clang_getTypedefDeclUnderlyingType,
    ---@type fun(C:CXCursor):CXType
    clang_getEnumDeclIntegerType = clang.clang_getEnumDeclIntegerType,
    ---@type fun(C:CXCursor):integer
    clang_getEnumConstantDeclValue = clang.clang_getEnumConstantDeclValue,
    ---@type fun(C:CXCursor):integer
    clang_getEnumConstantDeclUnsignedValue = clang.clang_getEnumConstantDeclUnsignedValue,
    ---@type fun(C:CXCursor):integer
    clang_getFieldDeclBitWidth = clang.clang_getFieldDeclBitWidth,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_getNumArguments = clang.clang_Cursor_getNumArguments,
    ---@type fun(C:CXCursor, i:integer):CXCursor
    clang_Cursor_getArgument = clang.clang_Cursor_getArgument,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_getNumTemplateArguments = clang.clang_Cursor_getNumTemplateArguments,
    ---@type fun(C:CXCursor, I:integer):integer
    clang_Cursor_getTemplateArgumentKind = clang.clang_Cursor_getTemplateArgumentKind,
    ---@type fun(C:CXCursor, I:integer):CXType
    clang_Cursor_getTemplateArgumentType = clang.clang_Cursor_getTemplateArgumentType,
    ---@type fun(C:CXCursor, I:integer):integer
    clang_Cursor_getTemplateArgumentValue = clang.clang_Cursor_getTemplateArgumentValue,
    ---@type fun(C:CXCursor, I:integer):integer
    clang_Cursor_getTemplateArgumentUnsignedValue = clang.clang_Cursor_getTemplateArgumentUnsignedValue,
    ---@type fun(A:CXType, B:CXType):integer
    clang_equalTypes = clang.clang_equalTypes,
    ---@type fun(T:CXType):CXType
    clang_getCanonicalType = clang.clang_getCanonicalType,
    ---@type fun(T:CXType):integer
    clang_isConstQualifiedType = clang.clang_isConstQualifiedType,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isMacroFunctionLike = clang.clang_Cursor_isMacroFunctionLike,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isMacroBuiltin = clang.clang_Cursor_isMacroBuiltin,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isFunctionInlined = clang.clang_Cursor_isFunctionInlined,
    ---@type fun(T:CXType):integer
    clang_isVolatileQualifiedType = clang.clang_isVolatileQualifiedType,
    ---@type fun(T:CXType):integer
    clang_isRestrictQualifiedType = clang.clang_isRestrictQualifiedType,
    ---@type fun(T:CXType):integer
    clang_getAddressSpace = clang.clang_getAddressSpace,
    ---@type fun(CT:CXType):CXString
    clang_getTypedefName = clang.clang_getTypedefName,
    ---@type fun(T:CXType):CXType
    clang_getPointeeType = clang.clang_getPointeeType,
    ---@type fun(T:CXType):CXCursor
    clang_getTypeDeclaration = clang.clang_getTypeDeclaration,
    ---@type fun(C:CXCursor):CXString
    clang_getDeclObjCTypeEncoding = clang.clang_getDeclObjCTypeEncoding,
    ---@type fun(type:CXType):CXString
    clang_Type_getObjCEncoding = clang.clang_Type_getObjCEncoding,
    ---@type fun(K:integer):CXString
    clang_getTypeKindSpelling = clang.clang_getTypeKindSpelling,
    ---@type fun(T:CXType):integer
    clang_getFunctionTypeCallingConv = clang.clang_getFunctionTypeCallingConv,
    ---@type fun(T:CXType):CXType
    clang_getResultType = clang.clang_getResultType,
    ---@type fun(T:CXType):integer
    clang_getExceptionSpecificationType = clang.clang_getExceptionSpecificationType,
    ---@type fun(T:CXType):integer
    clang_getNumArgTypes = clang.clang_getNumArgTypes,
    ---@type fun(T:CXType, i:integer):CXType
    clang_getArgType = clang.clang_getArgType,
    ---@type fun(T:CXType):CXType
    clang_Type_getObjCObjectBaseType = clang.clang_Type_getObjCObjectBaseType,
    ---@type fun(T:CXType):integer
    clang_Type_getNumObjCProtocolRefs = clang.clang_Type_getNumObjCProtocolRefs,
    ---@type fun(T:CXType, i:integer):CXCursor
    clang_Type_getObjCProtocolDecl = clang.clang_Type_getObjCProtocolDecl,
    ---@type fun(T:CXType):integer
    clang_Type_getNumObjCTypeArgs = clang.clang_Type_getNumObjCTypeArgs,
    ---@type fun(T:CXType, i:integer):CXType
    clang_Type_getObjCTypeArg = clang.clang_Type_getObjCTypeArg,
    ---@type fun(T:CXType):integer
    clang_isFunctionTypeVariadic = clang.clang_isFunctionTypeVariadic,
    ---@type fun(C:CXCursor):CXType
    clang_getCursorResultType = clang.clang_getCursorResultType,
    ---@type fun(C:CXCursor):integer
    clang_getCursorExceptionSpecificationType = clang.clang_getCursorExceptionSpecificationType,
    ---@type fun(T:CXType):integer
    clang_isPODType = clang.clang_isPODType,
    ---@type fun(T:CXType):CXType
    clang_getElementType = clang.clang_getElementType,
    ---@type fun(T:CXType):integer
    clang_getNumElements = clang.clang_getNumElements,
    ---@type fun(T:CXType):CXType
    clang_getArrayElementType = clang.clang_getArrayElementType,
    ---@type fun(T:CXType):integer
    clang_getArraySize = clang.clang_getArraySize,
    ---@type fun(T:CXType):CXType
    clang_Type_getNamedType = clang.clang_Type_getNamedType,
    ---@type fun(T:CXType):integer
    clang_Type_isTransparentTagTypedef = clang.clang_Type_isTransparentTagTypedef,
    ---@type fun(T:CXType):integer
    clang_Type_getNullability = clang.clang_Type_getNullability,
    ---@type fun(T:CXType):integer
    clang_Type_getAlignOf = clang.clang_Type_getAlignOf,
    ---@type fun(T:CXType):CXType
    clang_Type_getClassType = clang.clang_Type_getClassType,
    ---@type fun(T:CXType):integer
    clang_Type_getSizeOf = clang.clang_Type_getSizeOf,
    ---@type fun(T:CXType, S:string):integer
    clang_Type_getOffsetOf = clang.clang_Type_getOffsetOf,
    ---@type fun(T:CXType):CXType
    clang_Type_getModifiedType = clang.clang_Type_getModifiedType,
    ---@type fun(CT:CXType):CXType
    clang_Type_getValueType = clang.clang_Type_getValueType,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_getOffsetOfField = clang.clang_Cursor_getOffsetOfField,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isAnonymous = clang.clang_Cursor_isAnonymous,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isAnonymousRecordDecl = clang.clang_Cursor_isAnonymousRecordDecl,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isInlineNamespace = clang.clang_Cursor_isInlineNamespace,
    ---@type fun(T:CXType):integer
    clang_Type_getNumTemplateArguments = clang.clang_Type_getNumTemplateArguments,
    ---@type fun(T:CXType, i:integer):CXType
    clang_Type_getTemplateArgumentAsType = clang.clang_Type_getTemplateArgumentAsType,
    ---@type fun(T:CXType):integer
    clang_Type_getCXXRefQualifier = clang.clang_Type_getCXXRefQualifier,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isBitField = clang.clang_Cursor_isBitField,
    ---@type fun(param1:CXCursor):integer
    clang_isVirtualBase = clang.clang_isVirtualBase,
    ---@type fun(param1:CXCursor):integer
    clang_getCXXAccessSpecifier = clang.clang_getCXXAccessSpecifier,
    ---@type fun(param1:CXCursor):integer
    clang_Cursor_getStorageClass = clang.clang_Cursor_getStorageClass,
    ---@type fun(cursor:CXCursor):integer
    clang_getNumOverloadedDecls = clang.clang_getNumOverloadedDecls,
    ---@type fun(cursor:CXCursor, index:integer):CXCursor
    clang_getOverloadedDecl = clang.clang_getOverloadedDecl,
    ---@type fun(param1:CXCursor):CXType
    clang_getIBOutletCollectionType = clang.clang_getIBOutletCollectionType,
    ---@type fun(parent:CXCursor, visitor:CXCursorVisitor, client_data:CXClientData):integer
    clang_visitChildren = clang.clang_visitChildren,
    ---@type fun(param1:CXCursor):CXString
    clang_getCursorUSR = clang.clang_getCursorUSR,
    ---@type fun(class_name:string):CXString
    clang_constructUSR_ObjCClass = clang.clang_constructUSR_ObjCClass,
    ---@type fun(class_name:string, category_name:string):CXString
    clang_constructUSR_ObjCCategory = clang.clang_constructUSR_ObjCCategory,
    ---@type fun(protocol_name:string):CXString
    clang_constructUSR_ObjCProtocol = clang.clang_constructUSR_ObjCProtocol,
    ---@type fun(name:string, classUSR:CXString):CXString
    clang_constructUSR_ObjCIvar = clang.clang_constructUSR_ObjCIvar,
    ---@type fun(name:string, isInstanceMethod:integer, classUSR:CXString):CXString
    clang_constructUSR_ObjCMethod = clang.clang_constructUSR_ObjCMethod,
    ---@type fun(property:string, classUSR:CXString):CXString
    clang_constructUSR_ObjCProperty = clang.clang_constructUSR_ObjCProperty,
    ---@type fun(param1:CXCursor):CXString
    clang_getCursorSpelling = clang.clang_getCursorSpelling,
    ---@type fun(param1:CXCursor, pieceIndex:integer, options:integer):CXSourceRange
    clang_Cursor_getSpellingNameRange = clang.clang_Cursor_getSpellingNameRange,
    ---@type fun(Policy:CXPrintingPolicy, Property:integer):integer
    clang_PrintingPolicy_getProperty = clang.clang_PrintingPolicy_getProperty,
    ---@type fun(Policy:CXPrintingPolicy, Property:integer, Value:integer):nil
    clang_PrintingPolicy_setProperty = clang.clang_PrintingPolicy_setProperty,
    ---@type fun(param1:CXCursor):CXPrintingPolicy
    clang_getCursorPrintingPolicy = clang.clang_getCursorPrintingPolicy,
    ---@type fun(Policy:CXPrintingPolicy):nil
    clang_PrintingPolicy_dispose = clang.clang_PrintingPolicy_dispose,
    ---@type fun(Cursor:CXCursor, Policy:CXPrintingPolicy):CXString
    clang_getCursorPrettyPrinted = clang.clang_getCursorPrettyPrinted,
    ---@type fun(param1:CXCursor):CXString
    clang_getCursorDisplayName = clang.clang_getCursorDisplayName,
    ---@type fun(param1:CXCursor):CXCursor
    clang_getCursorReferenced = clang.clang_getCursorReferenced,
    ---@type fun(param1:CXCursor):CXCursor
    clang_getCursorDefinition = clang.clang_getCursorDefinition,
    ---@type fun(param1:CXCursor):integer
    clang_isCursorDefinition = clang.clang_isCursorDefinition,
    ---@type fun(param1:CXCursor):CXCursor
    clang_getCanonicalCursor = clang.clang_getCanonicalCursor,
    ---@type fun(param1:CXCursor):integer
    clang_Cursor_getObjCSelectorIndex = clang.clang_Cursor_getObjCSelectorIndex,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isDynamicCall = clang.clang_Cursor_isDynamicCall,
    ---@type fun(C:CXCursor):CXType
    clang_Cursor_getReceiverType = clang.clang_Cursor_getReceiverType,
    ---@type fun(C:CXCursor, reserved:integer):integer
    clang_Cursor_getObjCPropertyAttributes = clang.clang_Cursor_getObjCPropertyAttributes,
    ---@type fun(C:CXCursor):CXString
    clang_Cursor_getObjCPropertyGetterName = clang.clang_Cursor_getObjCPropertyGetterName,
    ---@type fun(C:CXCursor):CXString
    clang_Cursor_getObjCPropertySetterName = clang.clang_Cursor_getObjCPropertySetterName,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_getObjCDeclQualifiers = clang.clang_Cursor_getObjCDeclQualifiers,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isObjCOptional = clang.clang_Cursor_isObjCOptional,
    ---@type fun(C:CXCursor):integer
    clang_Cursor_isVariadic = clang.clang_Cursor_isVariadic,
    ---@type fun(C:CXCursor, language:any, definedIn:any, isGenerated:any):integer
    clang_Cursor_isExternalSymbol = clang.clang_Cursor_isExternalSymbol,
    ---@type fun(C:CXCursor):CXSourceRange
    clang_Cursor_getCommentRange = clang.clang_Cursor_getCommentRange,
    ---@type fun(C:CXCursor):CXString
    clang_Cursor_getRawCommentText = clang.clang_Cursor_getRawCommentText,
    ---@type fun(C:CXCursor):CXString
    clang_Cursor_getBriefCommentText = clang.clang_Cursor_getBriefCommentText,
    ---@type fun(param1:CXCursor):CXString
    clang_Cursor_getMangling = clang.clang_Cursor_getMangling,
    ---@type fun(param1:CXCursor):any
    clang_Cursor_getCXXManglings = clang.clang_Cursor_getCXXManglings,
    ---@type fun(param1:CXCursor):any
    clang_Cursor_getObjCManglings = clang.clang_Cursor_getObjCManglings,
    ---@type fun(C:CXCursor):CXModule
    clang_Cursor_getModule = clang.clang_Cursor_getModule,
    ---@type fun(param1:CXTranslationUnit, param2:CXFile):CXModule
    clang_getModuleForFile = clang.clang_getModuleForFile,
    ---@type fun(Module:CXModule):CXFile
    clang_Module_getASTFile = clang.clang_Module_getASTFile,
    ---@type fun(Module:CXModule):CXModule
    clang_Module_getParent = clang.clang_Module_getParent,
    ---@type fun(Module:CXModule):CXString
    clang_Module_getName = clang.clang_Module_getName,
    ---@type fun(Module:CXModule):CXString
    clang_Module_getFullName = clang.clang_Module_getFullName,
    ---@type fun(Module:CXModule):integer
    clang_Module_isSystem = clang.clang_Module_isSystem,
    ---@type fun(param1:CXTranslationUnit, Module:CXModule):integer
    clang_Module_getNumTopLevelHeaders = clang.clang_Module_getNumTopLevelHeaders,
    ---@type fun(param1:CXTranslationUnit, Module:CXModule, Index:integer):CXFile
    clang_Module_getTopLevelHeader = clang.clang_Module_getTopLevelHeader,
    ---@type fun(C:CXCursor):integer
    clang_CXXConstructor_isConvertingConstructor = clang.clang_CXXConstructor_isConvertingConstructor,
    ---@type fun(C:CXCursor):integer
    clang_CXXConstructor_isCopyConstructor = clang.clang_CXXConstructor_isCopyConstructor,
    ---@type fun(C:CXCursor):integer
    clang_CXXConstructor_isDefaultConstructor = clang.clang_CXXConstructor_isDefaultConstructor,
    ---@type fun(C:CXCursor):integer
    clang_CXXConstructor_isMoveConstructor = clang.clang_CXXConstructor_isMoveConstructor,
    ---@type fun(C:CXCursor):integer
    clang_CXXField_isMutable = clang.clang_CXXField_isMutable,
    ---@type fun(C:CXCursor):integer
    clang_CXXMethod_isDefaulted = clang.clang_CXXMethod_isDefaulted,
    ---@type fun(C:CXCursor):integer
    clang_CXXMethod_isPureVirtual = clang.clang_CXXMethod_isPureVirtual,
    ---@type fun(C:CXCursor):integer
    clang_CXXMethod_isStatic = clang.clang_CXXMethod_isStatic,
    ---@type fun(C:CXCursor):integer
    clang_CXXMethod_isVirtual = clang.clang_CXXMethod_isVirtual,
    ---@type fun(C:CXCursor):integer
    clang_CXXRecord_isAbstract = clang.clang_CXXRecord_isAbstract,
    ---@type fun(C:CXCursor):integer
    clang_EnumDecl_isScoped = clang.clang_EnumDecl_isScoped,
    ---@type fun(C:CXCursor):integer
    clang_CXXMethod_isConst = clang.clang_CXXMethod_isConst,
    ---@type fun(C:CXCursor):integer
    clang_getTemplateCursorKind = clang.clang_getTemplateCursorKind,
    ---@type fun(C:CXCursor):CXCursor
    clang_getSpecializedCursorTemplate = clang.clang_getSpecializedCursorTemplate,
    ---@type fun(C:CXCursor, NameFlags:integer, PieceIndex:integer):CXSourceRange
    clang_getCursorReferenceNameRange = clang.clang_getCursorReferenceNameRange,
    ---@type fun(TU:CXTranslationUnit, Location:CXSourceLocation):any
    clang_getToken = clang.clang_getToken,
    ---@type fun(param1:CXToken):integer
    clang_getTokenKind = clang.clang_getTokenKind,
    ---@type fun(param1:CXTranslationUnit, param2:CXToken):CXString
    clang_getTokenSpelling = clang.clang_getTokenSpelling,
    ---@type fun(param1:CXTranslationUnit, param2:CXToken):CXSourceLocation
    clang_getTokenLocation = clang.clang_getTokenLocation,
    ---@type fun(param1:CXTranslationUnit, param2:CXToken):CXSourceRange
    clang_getTokenExtent = clang.clang_getTokenExtent,
    ---@type fun(TU:CXTranslationUnit, Range:CXSourceRange, Tokens:any, NumTokens:any):nil
    clang_tokenize = clang.clang_tokenize,
    ---@type fun(TU:CXTranslationUnit, Tokens:any, NumTokens:integer, Cursors:any):nil
    clang_annotateTokens = clang.clang_annotateTokens,
    ---@type fun(TU:CXTranslationUnit, Tokens:any, NumTokens:integer):nil
    clang_disposeTokens = clang.clang_disposeTokens,
    ---@type fun(Kind:integer):CXString
    clang_getCursorKindSpelling = clang.clang_getCursorKindSpelling,
    ---@type fun(param1:CXCursor, startBuf:any, endBuf:any, startLine:any, startColumn:any, endLine:any, endColumn:any):nil
    clang_getDefinitionSpellingAndExtent = clang.clang_getDefinitionSpellingAndExtent,
    ---@type fun():nil
    clang_enableStackTraces = clang.clang_enableStackTraces,
    ---@type fun(fn:any, user_data:any, stack_size:integer):nil
    clang_executeOnThread = clang.clang_executeOnThread,
    ---@type fun(completion_string:CXCompletionString, chunk_number:integer):integer
    clang_getCompletionChunkKind = clang.clang_getCompletionChunkKind,
    ---@type fun(completion_string:CXCompletionString, chunk_number:integer):CXString
    clang_getCompletionChunkText = clang.clang_getCompletionChunkText,
    ---@type fun(completion_string:CXCompletionString, chunk_number:integer):CXCompletionString
    clang_getCompletionChunkCompletionString = clang.clang_getCompletionChunkCompletionString,
    ---@type fun(completion_string:CXCompletionString):integer
    clang_getNumCompletionChunks = clang.clang_getNumCompletionChunks,
    ---@type fun(completion_string:CXCompletionString):integer
    clang_getCompletionPriority = clang.clang_getCompletionPriority,
    ---@type fun(completion_string:CXCompletionString):integer
    clang_getCompletionAvailability = clang.clang_getCompletionAvailability,
    ---@type fun(completion_string:CXCompletionString):integer
    clang_getCompletionNumAnnotations = clang.clang_getCompletionNumAnnotations,
    ---@type fun(completion_string:CXCompletionString, annotation_number:integer):CXString
    clang_getCompletionAnnotation = clang.clang_getCompletionAnnotation,
    ---@type fun(completion_string:CXCompletionString, kind:any):CXString
    clang_getCompletionParent = clang.clang_getCompletionParent,
    ---@type fun(completion_string:CXCompletionString):CXString
    clang_getCompletionBriefComment = clang.clang_getCompletionBriefComment,
    ---@type fun(cursor:CXCursor):CXCompletionString
    clang_getCursorCompletionString = clang.clang_getCursorCompletionString,
    ---@type fun(results:any, completion_index:integer):integer
    clang_getCompletionNumFixIts = clang.clang_getCompletionNumFixIts,
    ---@type fun(results:any, completion_index:integer, fixit_index:integer, replacement_range:any):CXString
    clang_getCompletionFixIt = clang.clang_getCompletionFixIt,
    ---@type fun():integer
    clang_defaultCodeCompleteOptions = clang.clang_defaultCodeCompleteOptions,
    ---@type fun(TU:CXTranslationUnit, complete_filename:string, complete_line:integer, complete_column:integer, unsaved_files:any, num_unsaved_files:integer, options:integer):any
    clang_codeCompleteAt = clang.clang_codeCompleteAt,
    ---@type fun(Results:any, NumResults:integer):nil
    clang_sortCodeCompletionResults = clang.clang_sortCodeCompletionResults,
    ---@type fun(Results:any):nil
    clang_disposeCodeCompleteResults = clang.clang_disposeCodeCompleteResults,
    ---@type fun(Results:any):integer
    clang_codeCompleteGetNumDiagnostics = clang.clang_codeCompleteGetNumDiagnostics,
    ---@type fun(Results:any, Index:integer):CXDiagnostic
    clang_codeCompleteGetDiagnostic = clang.clang_codeCompleteGetDiagnostic,
    ---@type fun(Results:any):integer
    clang_codeCompleteGetContexts = clang.clang_codeCompleteGetContexts,
    ---@type fun(Results:any, IsIncomplete:any):integer
    clang_codeCompleteGetContainerKind = clang.clang_codeCompleteGetContainerKind,
    ---@type fun(Results:any):CXString
    clang_codeCompleteGetContainerUSR = clang.clang_codeCompleteGetContainerUSR,
    ---@type fun(Results:any):CXString
    clang_codeCompleteGetObjCSelector = clang.clang_codeCompleteGetObjCSelector,
    ---@type fun():CXString
    clang_getClangVersion = clang.clang_getClangVersion,
    ---@type fun(isEnabled:integer):nil
    clang_toggleCrashRecovery = clang.clang_toggleCrashRecovery,
    ---@type fun(tu:CXTranslationUnit, visitor:CXInclusionVisitor, client_data:CXClientData):nil
    clang_getInclusions = clang.clang_getInclusions,
    ---@type fun(C:CXCursor):CXEvalResult
    clang_Cursor_Evaluate = clang.clang_Cursor_Evaluate,
    ---@type fun(E:CXEvalResult):integer
    clang_EvalResult_getKind = clang.clang_EvalResult_getKind,
    ---@type fun(E:CXEvalResult):integer
    clang_EvalResult_getAsInt = clang.clang_EvalResult_getAsInt,
    ---@type fun(E:CXEvalResult):integer
    clang_EvalResult_getAsLongLong = clang.clang_EvalResult_getAsLongLong,
    ---@type fun(E:CXEvalResult):integer
    clang_EvalResult_isUnsignedInt = clang.clang_EvalResult_isUnsignedInt,
    ---@type fun(E:CXEvalResult):integer
    clang_EvalResult_getAsUnsigned = clang.clang_EvalResult_getAsUnsigned,
    ---@type fun(E:CXEvalResult):number
    clang_EvalResult_getAsDouble = clang.clang_EvalResult_getAsDouble,
    ---@type fun(E:CXEvalResult):string
    clang_EvalResult_getAsStr = clang.clang_EvalResult_getAsStr,
    ---@type fun(E:CXEvalResult):nil
    clang_EvalResult_dispose = clang.clang_EvalResult_dispose,
    ---@type fun(path:string):CXRemapping
    clang_getRemappings = clang.clang_getRemappings,
    ---@type fun(filePaths:any, numFiles:integer):CXRemapping
    clang_getRemappingsFromFileList = clang.clang_getRemappingsFromFileList,
    ---@type fun(param1:CXRemapping):integer
    clang_remap_getNumFiles = clang.clang_remap_getNumFiles,
    ---@type fun(param1:CXRemapping, index:integer, original:any, transformed:any):nil
    clang_remap_getFilenames = clang.clang_remap_getFilenames,
    ---@type fun(param1:CXRemapping):nil
    clang_remap_dispose = clang.clang_remap_dispose,
    ---@type fun(cursor:CXCursor, file:CXFile, visitor:CXCursorAndRangeVisitor):integer
    clang_findReferencesInFile = clang.clang_findReferencesInFile,
    ---@type fun(TU:CXTranslationUnit, file:CXFile, visitor:CXCursorAndRangeVisitor):integer
    clang_findIncludesInFile = clang.clang_findIncludesInFile,
    ---@type fun(param1:integer):integer
    clang_index_isEntityObjCContainerKind = clang.clang_index_isEntityObjCContainerKind,
    ---@type fun(param1:any):any
    clang_index_getObjCContainerDeclInfo = clang.clang_index_getObjCContainerDeclInfo,
    ---@type fun(param1:any):any
    clang_index_getObjCInterfaceDeclInfo = clang.clang_index_getObjCInterfaceDeclInfo,
    ---@type fun(param1:any):any
    clang_index_getObjCCategoryDeclInfo = clang.clang_index_getObjCCategoryDeclInfo,
    ---@type fun(param1:any):any
    clang_index_getObjCProtocolRefListInfo = clang.clang_index_getObjCProtocolRefListInfo,
    ---@type fun(param1:any):any
    clang_index_getObjCPropertyDeclInfo = clang.clang_index_getObjCPropertyDeclInfo,
    ---@type fun(param1:any):any
    clang_index_getIBOutletCollectionAttrInfo = clang.clang_index_getIBOutletCollectionAttrInfo,
    ---@type fun(param1:any):any
    clang_index_getCXXClassDeclInfo = clang.clang_index_getCXXClassDeclInfo,
    ---@type fun(param1:any):CXIdxClientContainer
    clang_index_getClientContainer = clang.clang_index_getClientContainer,
    ---@type fun(param1:any, param2:CXIdxClientContainer):nil
    clang_index_setClientContainer = clang.clang_index_setClientContainer,
    ---@type fun(param1:any):CXIdxClientEntity
    clang_index_getClientEntity = clang.clang_index_getClientEntity,
    ---@type fun(param1:any, param2:CXIdxClientEntity):nil
    clang_index_setClientEntity = clang.clang_index_setClientEntity,
    ---@type fun(CIdx:CXIndex):CXIndexAction
    clang_IndexAction_create = clang.clang_IndexAction_create,
    ---@type fun(param1:CXIndexAction):nil
    clang_IndexAction_dispose = clang.clang_IndexAction_dispose,
    ---@type fun(param1:CXIndexAction, client_data:CXClientData, index_callbacks:any, index_callbacks_size:integer, index_options:integer, source_filename:string, command_line_args:any, num_command_line_args:integer, unsaved_files:any, num_unsaved_files:integer, out_TU:any, TU_options:integer):integer
    clang_indexSourceFile = clang.clang_indexSourceFile,
    ---@type fun(param1:CXIndexAction, client_data:CXClientData, index_callbacks:any, index_callbacks_size:integer, index_options:integer, source_filename:string, command_line_args:any, num_command_line_args:integer, unsaved_files:any, num_unsaved_files:integer, out_TU:any, TU_options:integer):integer
    clang_indexSourceFileFullArgv = clang.clang_indexSourceFileFullArgv,
    ---@type fun(param1:CXIndexAction, client_data:CXClientData, index_callbacks:any, index_callbacks_size:integer, index_options:integer, param6:CXTranslationUnit):integer
    clang_indexTranslationUnit = clang.clang_indexTranslationUnit,
    ---@type fun(loc:CXIdxLoc, indexFile:any, file:any, line:any, column:any, offset:any):nil
    clang_indexLoc_getFileLocation = clang.clang_indexLoc_getFileLocation,
    ---@type fun(loc:CXIdxLoc):CXSourceLocation
    clang_indexLoc_getCXSourceLocation = clang.clang_indexLoc_getCXSourceLocation,
    ---@type fun(T:CXType, visitor:CXFieldVisitor, client_data:CXClientData):integer
    clang_Type_visitFields = clang.clang_Type_visitFields,
    ---@type fun(string:CXString):string
    clang_getCString = clang.clang_getCString,
    ---@type fun(string:CXString):nil
    clang_disposeString = clang.clang_disposeString,
    ---@type fun(set:any):nil
    clang_disposeStringSet = clang.clang_disposeStringSet,
}
return M
