-- this is generated by luajitffi
local ffi = require('ffi')

-- cdef
require('clang.cdef.corecrt')
require('clang.cdef.CXString')
require('clang.cdef.vcruntime')
require('clang.cdef.CXErrorCode')
require('clang.cdef.Index')

local M = {
    libs = {},
    cache = {},
}
M.enums = {
}
-----------------------------------------------------------------------------
-- Shlwapi.dll
-----------------------------------------------------------------------------
local clang = ffi.load('Shlwapi')
M.cache.Shlwapi = Shlwapi
M.libs.Shlwapi = {
}
return M
